### ISSUE TITLE
progress

### ISSUE THREAD

**Issue by joshua1** [GeekyAnts/vue-native-core#1]
Hi @sanketsahusoft  is anything happening here. I see the support for route and v-model added to this which is really great. would all the other bit remain as is ? would be nice to use with nativebase

**Comment by sanketsahusoft** [comment]
We are making some progress. We don't have a definite timeline though.

We will keep you posted @joshua1

**Comment by joshua1** [comment]
am going to whip up something and start using this as it progresses

**Comment by RumbleFrog** [comment]
Saw this on the front page of HN, good work 👍

**Comment by neeraj-singh47** [comment]
@joshua1 The initial version has been launched. Go ahead and give it a try.
