### ISSUE TITLE
Does Vue Native allow access to React Native plugins?

### ISSUE THREAD

**Issue by smithb1994** [GeekyAnts/vue-native-core#10]
Does this library allow us to use React Native plugins like [react-native-camera](https://github.com/react-native-community/react-native-camera) in Vue Native?

Do we have access to accelerometer and other React Native plugins?

Is there any examples on how to do this?

**Comment by atilacamurca** [comment]
according to <https://vue-native.io/docs/react-native.html>

> Vue Native is like a syntactic sugar for React Native. We can import **any React Native component as it is and start using it**

I didn't find any examples...

**Comment by neeraj-singh47** [comment]
@smithb1994 Yes we do support most of the react-native plugins. Just follow the same procedures provided in react-native-camera and import the package within your component and and declare them as components based on your use case. We will update the docs with an example.

**Comment by NZX-DeSiGN** [comment]
Hi,

I'm also discovering the library and asked myself the same question. 
I've managed to use **react-native-render-html** plugin, so I guess other plugins will work the same way. 
I'm importing it globally, but locally also work.

In your script section of your **App.vue** file (before **export default**) add this :
```javascript
import Vue from 'vue-native-core'
import HTML from 'react-native-render-html'

Vue.component('html', HTML)
```
