### ISSUE TITLE
third party component

### ISSUE THREAD

**Issue by paliwalsam** [GeekyAnts/vue-native-core#100]
Hi team

Using:
==============
react-native
vue native
native base

Issue with:
=============
https://www.npmjs.com/package/react-native-timeago

&lt;nb-col&gt;
   &lt;TimeAgo time="2015-06-21T06:24:44.124Z" /&gt;
&lt;/nb-col&gt;

result 
Invariant violation: Element type is invalid

**Comment by neeraj-singh47** [comment]
@paliwalsam Have you declared TimeAgo as component within vue component?

**Comment by paliwalsam** [comment]
> @paliwalsam Have you declared TimeAgo as component within vue component?

import TimeAgo from 'react-native-timeago';
imported in vue file

could not find documentation for "declared component within vue component?"

**Comment by paliwalsam** [comment]
> @paliwalsam Have you declared TimeAgo as component within vue component?



> @paliwalsam Have you declared TimeAgo as component within vue component?

thanks, resolved

**Comment by drbarto** [comment]
@paliwalsam please close this issue if it is resolved.
