### ISSUE TITLE
Setup with Vue Native Cli does not work

### ISSUE THREAD

**Issue by javico2609** [GeekyAnts/vue-native-core#101]
Unable to resolve "../../App" from "node_modules\expo\AppEntry.js"

vue-native init vueNative
    blank template option

 npm 6.0.1
 node v8.11.1
 expo 2.2.5
 vue-native 0.0.3
 OS Win10

**Comment by neeraj-singh47** [comment]
@javico2609 Can you verify that your app.json contains a packagerOpts something like https://github.com/GeekyAnts/vue-native-core/issues/87#issuecomment-424078237

**Comment by alphaelf** [comment]
I have the same issue
i remove the  `App.js `

**Comment by javico2609** [comment]
@neeraj-singh47 

{
  "expo": {
    "name": "vueNative",
    "description": "This project is really great.",
    "slug": "vueNative",
    "privacy": "public",
    "sdkVersion": "31.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "packagerOpts": {
      "config": "rn-cli.config.js"
    }
  }
}

**Comment by tatsuyaueda** [comment]
I solved this problem.

It worked by rewriting rn-cli.config.js to the contents of the following comment.

https://github.com/GeekyAnts/vue-native-core/issues/91#issuecomment-431216570

Reactive Native 57+ seems to need this.

Thanks.

**Comment by kamontia** [comment]
I also face the same issue.

```bash
$ node -v
v9.9.0
$ npm -v
6.4.1
```

```json
$ cat package.json
{
  "name": "empty-project-template",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^31.0.2",
    "react": "16.5.1",
    "react-native": "0.57.4",
    "react-test-renderer": "^16.6.0-alpha.8af6728",
    "vue-native-core": "0.0.8",
    "vue-native-helper": "0.0.9"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "react-native-stylus-transformer": "^1.1.2",
    "stylus": "^0.54.5",
    "vue-native-scripts": "0.0.14"
  }
}
```


```js
$ cat rn-cli.config.js
const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-stylus-transformer")
    },
    resolver: {
      sourceExts: [...sourceExts, "styl"]
    }
  };
})();
```

```js
$ cat vueTransformerPlugin.js
var semver = require('semver');
var vueNaiveScripts = require("vue-native-scripts");
var reactNativeVersionString = require("react-native/package.json").version;
var reactNativeMinorVersion = semver(reactNativeVersionString).minor;

if (reactNativeMinorVersion >= 56) {
  upstreamTransformer = require("metro/src/reactNativeTransformer");
} else if (reactNativeMinorVersion >= 52) {
  upstreamTransformer = require("metro/src/transformer");
} else if (reactNativeMinorVersion >= 47) {
  upstreamTransformer = require("metro-bundler/src/transformer");
} else if (reactNativeMinorVersion === 46) {
  upstreamTransformer = require("metro-bundler/build/transformer");
} else {
  // handle RN <= 0.45
  var oldUpstreamTransformer = require("react-native/packager/transformer");
  upstreamTransformer = {
    transform({ src, filename, options }) {
      return oldUpstreamTransformer.transform(src, filename, options);
    }
  };
}
var vueExtensions = ["vue"]; // <-- Add other extensions if needed.

module.exports.transform = function({ src, filename, options }) {
  if (vueExtensions.some(ext => filename.endsWith("." + ext))) {
    return vueNaiveScripts.transform({ src, filename, options });
  }
  return upstreamTransformer.transform({ src, filename, options });
};
```

```bash
$ npm run ios
$ Unable to resolve "../../App" from "node_modules/expo/AppEntry.js"
```

What should I do to build successfully?

**Comment by sai3ot-priv** [comment]
I ran into the same issue but it seems that I found a working solution.
After a google-search it turns out, that vue-native needs the version 0.55.4. of  react-native 
So I changed it in my package.json but this causes some errors. So I also needed to downgrade the packages babel-preset-expo to 4.0.0 and expo to 29.0.0 and changed the sdk-version in my app.json to 29.0.0. Whatever this is my working 

package.json File:

```Json
{
  "name": "empty-project-template",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^29.0.0",
    "react": "16.5.0",
    "react-native": "0.55.4",
    "vue-native-core": "0.0.8",
    "vue-native-helper": "0.0.9"
  },
  "devDependencies": {
    "babel-preset-expo": "^4.0.0",
    "vue-native-scripts": "0.0.14"
  }
}
```

and my app.json file
```json
{
  "expo": {
    "name": "firstApp",
    "description": "This project is really great.",
    "slug": "firstApp",
    "privacy": "public",
    "sdkVersion": "29.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "packagerOpts": {
      "config": "rn-cli.config.js"
    }
  }
}
```

**Comment by lhernandezp** [comment]
> I ran into the same issue but it seems that I found a working solution.
> After a google-search it turns out, that vue-native needs the version 0.55.4. of react-native
> So I changed it in my package.json but this causes some errors. So I also needed to downgrade the packages babel-preset-expo to 4.0.0 and expo to 29.0.0 and changed the sdk-version in my app.json to 29.0.0. Whatever this is my working
> 
> package.json File:
> 
> ```json
> {
>   "name": "empty-project-template",
>   "main": "node_modules/expo/AppEntry.js",
>   "private": true,
>   "scripts": {
>     "start": "expo start",
>     "android": "expo start --android",
>     "ios": "expo start --ios",
>     "eject": "expo eject"
>   },
>   "dependencies": {
>     "expo": "^29.0.0",
>     "react": "16.5.0",
>     "react-native": "0.55.4",
>     "vue-native-core": "0.0.8",
>     "vue-native-helper": "0.0.9"
>   },
>   "devDependencies": {
>     "babel-preset-expo": "^4.0.0",
>     "vue-native-scripts": "0.0.14"
>   }
> }
> ```
> 
> and my app.json file
> 
> ```json
> {
>   "expo": {
>     "name": "firstApp",
>     "description": "This project is really great.",
>     "slug": "firstApp",
>     "privacy": "public",
>     "sdkVersion": "29.0.0",
>     "platforms": [
>       "ios",
>       "android"
>     ],
>     "version": "1.0.0",
>     "orientation": "portrait",
>     "icon": "./assets/icon.png",
>     "splash": {
>       "image": "./assets/splash.png",
>       "resizeMode": "contain",
>       "backgroundColor": "#ffffff"
>     },
>     "updates": {
>       "fallbackToCacheTimeout": 0
>     },
>     "assetBundlePatterns": [
>       "**/*"
>     ],
>     "ios": {
>       "supportsTablet": true
>     },
>     "packagerOpts": {
>       "config": "rn-cli.config.js"
>     }
>   }
> }
> ```

Thanks!!!! , this is solution definitive!!

**Comment by juriuschakow** [comment]
> I ran into the same issue but it seems that I found a working solution.
> After a google-search it turns out, that vue-native needs the version 0.55.4. of react-native
> So I changed it in my package.json but this causes some errors. So I also needed to downgrade the packages babel-preset-expo to 4.0.0 and expo to 29.0.0 and changed the sdk-version in my app.json to 29.0.0. Whatever this is my working
> 
> package.json File:
> 
> ```json
> {
>   "name": "empty-project-template",
>   "main": "node_modules/expo/AppEntry.js",
>   "private": true,
>   "scripts": {
>     "start": "expo start",
>     "android": "expo start --android",
>     "ios": "expo start --ios",
>     "eject": "expo eject"
>   },
>   "dependencies": {
>     "expo": "^29.0.0",
>     "react": "16.5.0",
>     "react-native": "0.55.4",
>     "vue-native-core": "0.0.8",
>     "vue-native-helper": "0.0.9"
>   },
>   "devDependencies": {
>     "babel-preset-expo": "^4.0.0",
>     "vue-native-scripts": "0.0.14"
>   }
> }
> ```
> 
> and my app.json file
> 
> ```json
> {
>   "expo": {
>     "name": "firstApp",
>     "description": "This project is really great.",
>     "slug": "firstApp",
>     "privacy": "public",
>     "sdkVersion": "29.0.0",
>     "platforms": [
>       "ios",
>       "android"
>     ],
>     "version": "1.0.0",
>     "orientation": "portrait",
>     "icon": "./assets/icon.png",
>     "splash": {
>       "image": "./assets/splash.png",
>       "resizeMode": "contain",
>       "backgroundColor": "#ffffff"
>     },
>     "updates": {
>       "fallbackToCacheTimeout": 0
>     },
>     "assetBundlePatterns": [
>       "**/*"
>     ],
>     "ios": {
>       "supportsTablet": true
>     },
>     "packagerOpts": {
>       "config": "rn-cli.config.js"
>     }
>   }
> }
> ```

How have you done that? The downgrading i mean

**Comment by carlsunderman** [comment]
yes, i changed all three items sdk as well as babel expo and expo. still the same errors

**Comment by neeraj-singh47** [comment]
@carlsunderman Can you try clearing the cache as well

**Comment by hkvega01** [comment]
what are the commands needed for downgrade?

**Comment by 1quintana** [comment]
Using @lhernandezp works for me!

**Comment by LeafarDev** [comment]
Using @lhernandezp works if I use "expo start" instead of "npm start"

**Comment by flamehazw** [comment]
I also followed the documentation exactly but had same problem. I still don't know whats the issue, maybe this discussion will solve it later on . So, I cloned https://github.com/GeekyAnts/KitchenSink-Vue-Native, replaced App.vue with default welcome screen and ran the expo start --android with latest expo installed in emulator and it worked.

**Comment by jnav24** [comment]
I am also getting this error. If I try the "solution", I get more errors. @flamehazw solution in cloning the kitchen sink repo, replace the App.vue, delete all the js files in the src directory, and using the expo command (not npm or yarn commands) is the only thing working for me.

**Comment by ahmedsabry1996** [comment]
> Using the above "solution" still doesn't seem to fix the cannot find error.

after editing app.json & package.json run ` npm install ` then run `npm start `

**Comment by flamehazw** [comment]
@jnav24  hmm another best way to workaround is that just go to the playground link https://play.nativescript.org/?template=play-vue then download the file and "npm install" at the project directory and "tns run android --bundle" will work definitely but make sure you got your tns configuration setup is perfect before you start.  let me know if you are getting same problem again

**Comment by Jtaugner** [comment]
I spent 5 hours to decide fix this error. I hope this helps someone.
Just download and start "npm install". 
https://github.com/Jtaugner/vue-native/tree/master

**Comment by funabashi800** [comment]
> Using the above "solution" still doesn't seem to fix the cannot find error.

after editing package.json and app.json with @lhernandezp, try to delete node_modules and then reinstall again

```bash
rm -rf node_modules
npm cache clean --force
npm intstall
npm start
```

**Comment by umatbro** [comment]
> 
> 
> > Using the above "solution" still doesn't seem to fix the cannot find error.
> 
> after editing package.json and app.json with @lhernandezp, try to delete node_modules and then reinstall again
> 
> ```shell
> rm -rf node_modules
> npm cache clean --force
> npm intstall
> npm start
> ```

After doing this I get following error:

```
>npm start

> @ start C:\Users\mat\Documents\vue-native-proj
> expo start

This command requires Expo CLI.
Do you want to install it globally [Y/n]? y
Installing the package 'expo-cli'...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by funabashi800** [comment]
@umatbro Actually, this is all I did

* expo 2.7.1
* node v10.15.0
* npm 6.7.0

```bash
npm install -g react-native-cli
npm install -g create-react-native-app
npm install -g vue-native-cli
npm install -g expo-cli
```
And then, just edit like https://github.com/GeekyAnts/vue-native-core/issues/101#issuecomment-460497014

**Comment by neeraj-singh47** [comment]
This issue was related to expo installing RN > 0.55.4 by default. Support for RN > 0.55 has been added. Please update vue-native-cli to create  a new app with RN version > 0.55. [ Latest Release](https://github.com/GeekyAnts/vue-native-cli/releases/tag/0.0.6)
