### ISSUE TITLE
Third Party component require react-native Component

### ISSUE THREAD

**Issue by paliwalsam** [GeekyAnts/vue-native-core#104]
https://www.npmjs.com/package/react-native-ptr-control

This plugin Pull-to-Refresh require react-native component

&lt;PTRControl
  style={{flex: 1}}
  showsVerticalScrollIndicator={false}
  
  scrollComponent=**{'ScrollView'}**
  enableFooterInfinite={false}&gt;
  &lt;View&gt;
    &lt;Text&gt;{'scroll content'}&lt;/Text&gt;
  &lt;/View&gt;
&lt;/PTRControl&gt;

My Code is:

&lt;PTRControl
    :style="{flex: 1}"
    :showsVerticalScrollIndicator="false"
    :scrollComponent="ScrollView"
    :enableFooterInfinite="false"&gt;
  &lt;nb-content&gt; 
      &lt;nb-list&gt;
          &lt;nb-list-item v-for="item in listItemArr" :key="item.deal_id"&gt;
              &lt;image :style="{width: 60, height: 60}" :source="{uri: item.deal_image}" /&gt;
          &lt;/nb-list-item&gt;
      &lt;/nb-list&gt;
  &lt;/nb-content&gt;
&lt;/PTRControl&gt;

&lt;script&gt;
import axios from 'axios';
import TimeAgo from 'react-native-timeago';
import PTRControl from 'react-native-ptr-control';
import ConnectionUrls from '../../store/ConnectionUrls';
export default
{
    components: { TimeAgo,PTRControl }
}
&lt;/script&gt;

Getting:
Console.error: "[Vue.Warn]" Property or method "ScrollView" is not defined

**Comment by neeraj-singh47** [comment]
@paliwalsam Do not bind the ScrollView. It searches for `ScrollView` variable which is not declared. Remove the colon symbol and try again. `scrollComponent="ScrollView"`
