### ISSUE TITLE
Custom component two-way data binding

### ISSUE THREAD

**Issue by pakerwreah** [GeekyAnts/vue-native-core#105]
I read that vue-native already has support for v-model, but how can I create custom components in Vue using v-model / prop.sync without being able to $emit('input', value) or $emit('update:prop', value) ?

Is that feature exclusive to the transpiler?

**Comment by neeraj-singh47** [comment]
@pakerwreah $emit right now works only within component. You can try using v-model.

**Comment by pakerwreah** [comment]
I am using v-model, that's the problem. If I use v-model on my element (a wrapper around Input) and then try to use it like: props: ['value'] ... <Input v-model="value" />, then when I type it keeps erasing my text. That's not event the right way to do it, since props are readonly in normal Vue.
As a workaround I'm using slots so I can bind data with v-model directly into Input from the parent. I'm avoiding the use of textChanged callbacks because that's the main reason I gave up coding in React.

**Comment by neeraj-singh47** [comment]
@pakerwreah Since you are basically trying to modify the prop which is not allowed. It's empty. You can use onChangeText and call the parent function to modify the value
