### ISSUE TITLE
vue-native init doesn't work

### ISSUE THREAD

**Issue by kramer65** [GeekyAnts/vue-native-core#109]
Since, crna has been merged into expo I installed the expo cli using `npm install -g expo-cli`. After that I tried running `vue-native init blorkblork`, but I get an error saying:

> Please globally install create-react-native-app dependency

Is vue-native going to be compatible with the expo-cli in the (near) future?

**Comment by neeraj-singh47** [comment]
@kramer65 Yes we'll be removing the create-react-native-app dependency

**Comment by vahidalvandi** [comment]
return error 
'expo' is not recognized as an internal or external command,

**Comment by vahidalvandi** [comment]
after install  `npm install -g expo-cli`

aslo return this error 


```
 vue-native init webine
Installed Crna Version 2.10.1
prompt: Directory webine already exists. Continue?:  (no) yes
Creating Vue-Native webine App
[16:13:50] Input is required, but Expo CLI is in non-interactive mode.
--workflow: argument is required in non-interactive mode. Valid choices are: managed, advanced.
internal/process/main_thread_only.js:42
    return _chdir(directory);
```

**Comment by vahidalvandi** [comment]
it must use in cmd not in power shell

**Comment by farshidrezaei** [comment]
> it must use in cmd not in power shell

it's worked.

**Comment by vahidalvandi** [comment]
i fixed it in ubunto with set permission in npm global

```

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
export PATH=~/.npm-global/bin:$PATH


npm install npm@latest -g
npm install node@latest -g


npm install react-native-cli -g
npm install expo-cli -g
npm install -g vue-native-cli
```
