### ISSUE TITLE
Error while run on Android

### ISSUE THREAD

**Issue by tamacroft** [GeekyAnts/vue-native-core#111]
first project, when i run on Android/emulator, i got an error on terminal:
unable to resolve "../../App" from "node_modules/expo/AppEntry.js"

how fix it

**Comment by neeraj-singh47** [comment]
@tamacroft https://github.com/GeekyAnts/vue-native-core/issues/101#issuecomment-437606353

**Comment by neeraj-singh47** [comment]
This issue was related to expo installing RN > 0.55.4 by defualt. Support for RN > 0.55 has been added. Please update vue-native-cli to create  a new app with RN version > 0.55. [ Latest Release](https://github.com/GeekyAnts/vue-native-cli/releases/tag/0.0.6)
