### ISSUE TITLE
How to use i18n

### ISSUE THREAD

**Issue by slinker-hiwa** [GeekyAnts/vue-native-core#115]
I need use i18n to use multiple language in my app. Any way or library? Thanks.

**Comment by neeraj-singh47** [comment]
@slinker-hiwa http://kazupon.github.io/vue-i18n/guide/started.html#javascript. You can use Vue.use(VueI18n). You can look into this example for integration. https://github.com/GeekyAnts/vue-native-starter-app/blob/master/src/setup.vue

**Comment by slinker-hiwa** [comment]
@neeraj-singh47 thanks so much.

**Comment by francoisp** [comment]
Tried to use vue-i18n with vue-native-core, and I get this warning: [vue-i18n] vue-i18n (undefined) need to use Vue 2.0 or later (Vue: 0.1.4). Then when using $t() I get  this error: [Vue warn]: Property or method "$t" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
