### ISSUE TITLE
Unable to resolve "../../App" from "node_modules/expo/AppEntry.js"

### ISSUE THREAD

**Issue by 6ea** [GeekyAnts/vue-native-core#117]
ERROR

Unable to resolve "../../App" from "node_modules/expo/AppEntry.js"

After a day's tossing around, ask for help

**Comment by 6ea** [comment]
Building JavaScript bundle: 0%

**Comment by neeraj-singh47** [comment]
@6ea You can try using this method https://github.com/GeekyAnts/vue-native-core/issues/101#issuecomment-437606353

**Comment by elfelround** [comment]
in my case i had named App.js app.js in lowercases

**Comment by neeraj-singh47** [comment]
This issue was related to expo installing RN > 0.55.4 by default. Support for RN > 0.55 has been added. Please update vue-native-cli to create  a new app with RN version > 0.55. [ Latest Release](https://github.com/GeekyAnts/vue-native-cli/releases/tag/0.0.6)

**Comment by VanLaerAshley** [comment]
I have the same issue by upgrading to expo version 33.0.0

**Comment by VanLaerAshley** [comment]
Anyone solved this issue?

**Comment by mislam** [comment]
This issue is happening again from vue-native-core **v0.1.0** with **sdk34**

**Comment by VanLaerAshley** [comment]
Even when creating a new project from scratch, this error occurs in sdk33 and 34

**Comment by VanLaerAshley** [comment]
I managed to get newest vue native to work.

In app.json add
"sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"]
Inside
"packagerOpts"
`    "packagerOpts": {
      "sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"],
      "config": "metro.config.js"
    }`

**Comment by infnetdanpro** [comment]
Same problem, sdk 34:
ERROR Unable to resolve "../../App" from "node_modules/expo/AppEntry.js"
ERROR Building JavaScript bundle: error
INFO Building JavaScript bundle: 0%

**Comment by arrie1992** [comment]
> I managed to get it to work on sdk 34 and 33.
> 
> In app.json add
> "sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"]
> Inside
> "packagerOpts"
> ` "packagerOpts": { "sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"], "config": "metro.config.js" }`

Thank you, this solved it :)

**Comment by TranVanThaiSon** [comment]
> I managed to get it to work on sdk 34 and 33.
> 
> In app.json add
> "sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"]
> Inside
> "packagerOpts"
> ` "packagerOpts": { "sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"], "config": "metro.config.js" }`

Thank @6ea VanLaerAshley

**Comment by gillmoreno** [comment]
> I managed to get it to work on sdk 34 and 33.
> 
> In app.json add
> "sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"]
> Inside
> "packagerOpts"
> ` "packagerOpts": { "sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"], "config": "metro.config.js" }`

Solved it for me too!

**Comment by niklashaug** [comment]
I didn't have to change anything since the packagerOpts were like that already.
`"packagerOpts": {
      "config": "metro.config.js",
      "sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"],
    }`
My problem is that it only displays the App.js contents instead of the App.vue one's.
Tried a lot of things but unfortunately didn't get it working though.

**Comment by niklashaug** [comment]
Update: Got it working by moving out the App.js file, doing npm install and reloading Expo.
