### ISSUE TITLE
Please update library to work with React-Native 58+

### ISSUE THREAD

**Issue by lenvonsam** [GeekyAnts/vue-native-core#123]
React Native has published last version of 0.58.0, i hope vue native can also support the lastest version for react native

**Comment by neeraj-singh47** [comment]
Support for RN > 0.55 has been added. Please update vue-native-cli to create  a new app with RN version > 0.55. [ Latest Release](https://github.com/GeekyAnts/vue-native-cli/releases/tag/0.0.6)
