### ISSUE TITLE
after install and run emultor return this error

### ISSUE THREAD

**Issue by vahidalvandi** [GeekyAnts/vue-native-core#125]
D:\react-native\sss\node_modules\expo\AppEntry.js: Cannot find module
'vue-native-scripts'

**Comment by neeraj-singh47** [comment]
@vahidalvandi run `npm install vue-native-scripts`

**Comment by vahidalvandi** [comment]
maybe not work in shell git just work in cmd windows

**Comment by vahidalvandi** [comment]
please fix bugs in install
