### ISSUE TITLE
Setup with react native not working

### ISSUE THREAD

**Issue by bosyo** [GeekyAnts/vue-native-core#126]
Hi, 

Followed all steps in the documentation https://vue-native.io/docs/installation.html#Setup-with-React-Native but it doesn't seem to work.
I am having this "Unable to resolve module ./App". I have tried several configs but still no joy. I even cloned the KitchenSink Vue Native App just to test if it is working but i encountered the same issue.

Cheers!

**Comment by neeraj-singh47** [comment]
@bosyo Try creating a project using vue-native-cli. https://vue-native.io/docs/installation.html#Setup-with-Vue-Native-Cli
