### ISSUE TITLE
[Android] Dynamic URL image not working

### ISSUE THREAD

**Issue by dacastro4** [GeekyAnts/vue-native-core#130]
I'm trying to change an image element from a placeholder image to the user's profile picture from a http request.

my data has:

```
data() {
    return {
        photo: 'https://via.placeholder.com/150',
    }
}
```

and the template just has 
```
<Image :source="{ uri: photo }" :style="{ width: 100, height: 100, backgroundColor: '#fff' }" resizeMode="cover"/>
```

This is the result: 
![screen shot 2019-03-07 at 11 29 47 pm](https://user-images.githubusercontent.com/7808930/54007682-f10e6980-4130-11e9-99e9-672415884e20.png)

You have any idea what I could be? Am I doing something wrong?

**Comment by neeraj-singh47** [comment]
@dacastro4 Can you try giving it an extension. For Example. `https://via.placeholder.com/150.png`

**Comment by dacastro4** [comment]
@neeraj-singh47 I tried with another online image an still and it still works for iPhone perfectly

**Comment by neeraj-singh47** [comment]
@dacastro4 So it's not loading in android?

**Comment by dacastro4** [comment]
@neeraj-singh47 it is not. Only if the URL is static

**Comment by neeraj-singh47** [comment]
@dacastro4 Can you try using this image URL. `https://facebook.github.io/react-native/docs/assets/favicon.png`

**Comment by dacastro4** [comment]
I think the Android emulator is blocking my local images at least that what I think it is. I'm going to close it for now
