### ISSUE TITLE
How to avoid fullscreen

### ISSUE THREAD

**Issue by vortechron** [GeekyAnts/vue-native-core#131]
How to fix this????

![Capture](https://user-images.githubusercontent.com/22893960/54071665-d102b580-42aa-11e9-9411-3ac0207cc4ee.PNG)

**Comment by vortechron** [comment]
im running my app for the first time, and this what i got, my code has nothing to do with fullscreen, its just simple screen with header. pls halp!

**Comment by neeraj-singh47** [comment]
@vortechron https://facebook.github.io/react-native/docs/statusbar.html

**Comment by vortechron** [comment]
@neeraj-singh47 tq !! im hiding those status bar :D
