### ISSUE TITLE
Can't get Less working

### ISSUE THREAD

**Issue by jcbertolucci** [GeekyAnts/vue-native-core#134]
### I'm trying to use Less inside my components but I´m not being able to.

This error pops up when the screen is loading:

![Screenshot_20190315-134547](https://user-images.githubusercontent.com/24538294/54404828-d2a7ff80-4728-11e9-9f53-51f367def306.png)

**This is my code:**
```
<style lang="less">
  @container-color: #F5FCFF;
  @instructions-color: 333333;

  .spacer {
    padding: 20;
    color: @container-color;
  }
</style>
```

**This is my package.json file:**

```
"devDependencies": {
    "@babel/plugin-proposal-decorators": "^7.2.3",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/runtime": "^7.2.0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "23.6.0",
    "detox": "9.0.4",
    "eslint": "^5.12.1",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-react-native": "^3.6.0",
    "ios-sim": "^7.0.0",
    "jest": "23.6.0",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "metro-react-native-babel-preset": "0.53.0",
    "mocha": "^5.2.0",
    "node-sass": "^4.11.0",
    "pre-commit": "^1.2.2",
    "react-native-version": "^2.6.6",
    "react-test-renderer": "16.6.3",
    "sass-loader": "^7.1.0",
    "vue-native-scripts": "0.0.14"
  } 
```

If someone knows how to get it working, I would much appreciate your help.

Thanks.

**Comment by dacastro4** [comment]
Probably the webpack or whatever they use doesn't have the compiler for less inside the Vue files.

**Comment by neeraj-singh47** [comment]
@jcbertolucci You can make use of https://www.npmjs.com/package/react-native-less-transformer if you want to support `.less` files. You'll have to modify the vueTransformerPlugin.js so that for `.less` files it uses the less transformer.

**Comment by jcbertolucci** [comment]
@neeraj-singh47 thanks for your help. What exactly should I modify in vueTransformerPlugin.js? Sorry, first-timer here :)

**Comment by neeraj-singh47** [comment]
@jcbertolucci Here's an example where sass transformer was being used.

> var semver = require('semver');
var vueNaiveScripts = require("vue-native-scripts");
var reactNativeVersionString = require("react-native/package.json").version;
var reactNativeMinorVersion = semver(reactNativeVersionString).minor;
var SassTransformer = require("react-native-sass-transformer");
if (reactNativeMinorVersion >= 56) {
  upstreamTransformer = require("metro/src/reactNativeTransformer");
} else if (reactNativeMinorVersion >= 52) {
  upstreamTransformer = require("metro/src/transformer");
} else if (reactNativeMinorVersion >= 47) {
  upstreamTransformer = require("metro-bundler/src/transformer");
} else if (reactNativeMinorVersion === 46) {
  upstreamTransformer = require("metro-bundler/build/transformer");
} else {
  // handle RN <= 0.45
  var oldUpstreamTransformer = require("react-native/packager/transformer");
  upstreamTransformer = {
    transform({ src, filename, options }) {
      return oldUpstreamTransformer.transform(src, filename, options);
    }
  };
}
var vueExtensions = ["vue"]; // <-- Add other extensions if needed.
var sassExtensions = ["scss", "sass"];
module.exports.transform = function({ src, filename, options }) {
  if (vueExtensions.some(ext => filename.endsWith("." + ext))) {
    return vueNaiveScripts.transform({ src, filename, options });
  }
  if (sassExtensions.some(ext => filename.endsWith("." + ext))) {
    return SassTransformer.transform({src, filename, options});
  }
  return upstreamTransformer.transform({ src, filename, options });
};
