### ISSUE TITLE
Accessing Parent Component's css classes in child component

### ISSUE THREAD

**Issue by shanprsd** [GeekyAnts/vue-native-core#137]
I want a css class to be applied on every component which gets loaded using stack navigation.
I have defined the `router-view` tag on App.vue component this way:

```
<template>
<router-view></router-view>
</template>

<script>
import RouterView from "./src/router";

export default {
  components: { RouterView }
};
</script>
<style lang="scss">

.class-for-all {
  color: red
}
</style>
```
But accessing this class in the child component does not work.

**Comment by neeraj-singh47** [comment]
@shanprsd This is not feasible. However you can try implementing global styles using the approach mentioned in https://stackoverflow.com/questions/30853178/react-native-global-styles/41751407#41751407

**Comment by Dirshant** [comment]
I'm facing the same issue. I can't access to parents' CSS classes in the router-view
