### ISSUE TITLE
[Bounty- don't close until fix is accepted] $emit() doesn't work #25

### ISSUE THREAD

**Issue by birdlavv** [GeekyAnts/vue-native-core#138]
The workaround posted in #25 is not very scalable (can't implement global event bus).
This issue is to track the status of this feature for a bounty. Please do not close until an accepted fix is implemented. Thanks.

Similar to: https://github.com/GeekyAnts/vue-native-core/issues/25

https://www.bountysource.com/issues/72753924-bounty-don-t-close-until-fix-is-accepted-emit-doesn-t-work-25

**Comment by neeraj-singh47** [comment]
Please do upgrade the vue-native-template-complier to the latest version.
