### ISSUE TITLE
Opening in Expo issue

### ISSUE THREAD

**Issue by cfjedimaster** [GeekyAnts/vue-native-core#14]
I'm not sure if this is a vue-native-core issue or Expo or... something else. I used the `s` option to send a text to my phone with the running app. When it opened up Expo, it immediately crashed. I see this in terminal:

![image](https://user-images.githubusercontent.com/393660/41357477-e05d7f1c-6eeb-11e8-93ec-8d28c2e3a6a1.png)

**Comment by syumai** [comment]
@cfjedimaster
I've found that on Windows, vue-native-cli does not install required dependencies correctly.
You can solve this by running `yarn add vue-native-core vue-native-helpers` in your project.
I created PR to resolve this issue: https://github.com/GeekyAnts/vue-native-cli/issues/4

**Comment by JhonatanPereira** [comment]
I was having the same problem, and actually is `vue-native-helper` instead of `vue-native-helpers`. Thank you @syumai

**Comment by syumai** [comment]
@JhonatanPereira It was a mistake. Thank you for the correction! 😂
