### ISSUE TITLE
vueTransformerPlugin.js error

### ISSUE THREAD

**Issue by quantumwebco** [GeekyAnts/vue-native-core#140]
To recreate this error just follow the instructions 
```
npm install -g vue-native-cli
vue-native init <projectName> // Initializes crna project
cd <project-name>
npm install
npm start
```

In vueTransformerPlugin.js on line 2 there is an error. The 't' is missing from vueNaiveScripts.

```var vueNaiveScripts = require("vue-native-scripts");``` should be ```var vueNativeScripts = require("vue-native-scripts");```

Causes the error ```can't resolve module 'vue-native-scripts'``` and will not compile

**Comment by neeraj-singh47** [comment]
@quantumwebco It's a typo but it should work. Since there isn't a typo in requiring `vue-native-scripts`

**Comment by quantumwebco** [comment]
It doesn't work unless you change it. Or change all of the references to it

I gave up. vue-native is just terrible compared to other solutions.
