### ISSUE TITLE
how to use react-native-code-push in vue-native ?

### ISSUE THREAD

**Issue by kidboo9o** [GeekyAnts/vue-native-core#141]
how to use react-native-code-push in vue-native ?

**Comment by neeraj-singh47** [comment]
@kidboo9o Microsoft has pretty good documentation here. `https://github.com/Microsoft/react-native-code-push`. You'll have to follow the same instructions. The only change would be in the `index.js` file where the App component is being imported. You can wrap the root component using the codePush HOC in `index.js`
