### ISSUE TITLE
How to StackAction.reset with vue-native-router?

### ISSUE THREAD

**Issue by charlie-hssrr** [GeekyAnts/vue-native-core#143]
How do I stack action reset?

```
import { NavigationActions } from 'react-navigation'

const resetAction = NavigationActions.reset({
        index: 0, 
        key: null,
        actions: [
          NavigationActions.navigate({ routeName: 'Profile' })
        ],
})
this.navigation.dispatch(resetAction);
```

I get error:
![image](https://user-images.githubusercontent.com/50207699/57087763-0fdc4700-6d01-11e9-9311-d8bff263cf88.png)

**Comment by neeraj-singh47** [comment]
@charlie-hssrr You can refer this link for the usage `https://github.com/GeekyAnts/vue-native-starter-app/blob/master/src/screen/sidebar.vue`
