### ISSUE TITLE
Conditional groups with v-if on <template> ?

### ISSUE THREAD

**Issue by RohanTalip** [GeekyAnts/vue-native-core#147]
Hi,

Does Vue Native support Conditional Groups with `v-if` on `<template>` where `<template>` acts as an invisible wrapper? (See 
https://vuejs.org/v2/guide/conditional.html#Conditional-Groups-with-v-if-on-lt-template-gt )

I see that this doesn't work correctly with Vue Native (only A shows up):
```
<template>
  ...
  <template v-if="aCondition">
    <Text>A</Text>
    <Text>B</Text>
  </template>
  ...
</template>
```

This does work (both A and B show up) but adds a View element:
```
<template>
  ...
  <View v-if="aCondition">
    <Text>A</Text>
    <Text>B</Text>
  </View>
  ...
</template>
```

**Comment by neeraj-singh47** [comment]
It has been fixed by the latest vue-native-template-compiler version 0.13

**Comment by RohanTalip** [comment]
@neeraj-singh47 , thanks, but don't you also need to update the version of the vue-native-template-compiler dependency in the vue-native-scripts package?
https://github.com/GeekyAnts/vue-native-core/blob/44bdcfff47ce1f9955781d5db04bbffb90859bbd/packages/vue-native-scripts/package.json#L23 

`yarn upgrade` is not upgrading the vue-native-template-compiler package (it is still at version 0.0.12)

You are changing the first non-zero digit in the version number, so from my reading of https://yarnpkg.com/en/docs/dependency-versions#toc-caret-ranges  , the version specification ^0.0.12 does not match version 0.0.13.
