### ISSUE TITLE
vuex watch or subscribe

### ISSUE THREAD

**Issue by canturkm** [GeekyAnts/vue-native-core#149]
Hi,

I'm a newbie. I'm writing my app with Vue-Native. I use vuex for data sharing between components. Is there a way to use vuex watch or subscribe function on vue-native? I tried both of them. However, not worked on my vue-native app. Even vue's (not vuex) watchers not worked. 

Is there a way to watch a variable, or vuex state on vue-native?

I used this blog post as a reference for vuex watch and subscribe:
https://dev.to/viniciuskneves/watch-for-vuex-state-changes-2mgj

Reference for vue watchers:
https://vuejs.org/v2/guide/computed.html#Watchers

Thanks for help.

Edit: I solved using eventbus. however, if you answer for vuex, I appreciate it.

**Comment by neeraj-singh47** [comment]
@canturkm Vue watchers seem to be working. Can you share the code snippet?

**Comment by canturkm** [comment]
Hi,

My code is so complex, I'm gonna share related part:

There are 3 files: config.js, App.vue and Main.vue.

config.js defines the vuex store, App.vue is the main component that loads data and Main.vue first screen of my project and should wait for data loading initiated by App.vue component.

I try to show both event bus usage and Vue watcher usage. 

On this case, bus works, however vue watcher doesn't work.

config.js
`import Vue from "vue-native-core";
import Vuex from 'vuex';

Vue.use(Vuex);


const state = {
  dataGeneratedState: false,
  bus: new Vue(),
};
const getters = {
  dataGeneratedState: state => state.dataGeneratedState,

};
const mutations = {
  changeDataGeneratedState: function(state,status){
    console.log('data mutated ' +  status.toString());
    state.dataGeneratedState = status;
  },
};
const actions = {
  dataGenerated: function({commit}){
    console.log('data generated action triggered.');
    commit('changeDataGeneratedState', true);
  },
};

export const store = new Vuex.Store({state, getters, mutations, actions});`

App.vue
`
<template>
  <app-loading v-if="!isAppReady"> </app-loading>
      <app-navigation v-else />
</template>
<script>
import {store} from "./lib/config";

...
const AppNavigation = StackNavigator(
  {
    Main: MainScreen,
    Info: InfoScreen,
  },
  {
    initialRouteName: 'Main',
    headerMode: 'none',
    navigationOptions: {
      headerVisible: false,
    }
  }
);

...
await something();
store.dispatch('dataGenerated'); // vuex action call for watcher
store.state.bus.$emit('dataGeneratedBus'); // vue bus event emit
...
</script>`

Main.vue
`import {store} from "./lib/config";

data: function() {
   return {
     dataGeneratedState: store.state.dataGeneratedState,
   };
 },
 watch: {
   dataGeneratedState: function (newval, oldval) {
     console.log("data value changed to: " + JSON.stringify(newval));
   },
   mounted() {
   store.state.bus.$on('dataGeneratedBus',() => {
      console.log("dataGeneratedBus event emitted!");
      someFunction();

    });
   }
 },`


console log:
`...
data generated action triggered.
dataGenerated event emitted!
...`

if watcher worked, I should see "data value changed to: true" on the console.

Thanks for your help.

**Comment by icarter09** [comment]
@canturkm was this issue ever solved?

**Comment by canturkm** [comment]
Hi,

I solved my problem using eventbus. However, there is no progress with vuex. 

I tried both watch and subscribe, and none of them are working on my case. 

If you want to close the issue, I think you can close.

**Comment by icarter09** [comment]
@canturkm thanks for the update. I'm not able to close it out, but I believe you can since you are the author of the issue. Thanks.
