### ISSUE TITLE
Add differences with react-vue to docs

### ISSUE THREAD

**Issue by NZX-DeSiGN** [GeekyAnts/vue-native-core#15]
Hi,

I know everybody is asking you how it's working and what are differences with all others Vue solutions, but in your Medium article you only mention you've forked **react-vue**.
Can you tell us reasons and functionnalities you've added please ?

Thank you (and excuse my english)
Nicolas

**Comment by neeraj-singh47** [comment]
@NZX-DeSiGN React Vue only provides the compiler and it does not support v-model, classes and styles combined. Also you can use the vue-native-cli tool to create a vue-native app without writing any extra scripts.
