### ISSUE TITLE
Vue-Native.io/market is down

### ISSUE THREAD

**Issue by AtHeartEngineer** [GeekyAnts/vue-native-core#153]
**Error 526**
Invalid SSL certificate
_____________
Browser
Working
_____________
Cloudflare
Working
_____________
vue-native.io
Host Error
_____________
**What happened?**
The origin web server does not have a valid SSL certificate.

**If you're the owner of this website:**
The SSL certificate presented by the server did not pass validation. This could indicate an expired SSL certificate or a certificate that does not include the requested domain name. Please contact your hosting provider to ensure that an up-to-date and valid SSL certificate issued by a Certificate Authority is configured for this domain name on the origin server. Additional troubleshooting information here.

**Comment by sanketsahusoft** [comment]
We are looking into this.

**Comment by sanketsahusoft** [comment]
It's fixed!
