### ISSUE TITLE
return error in npm start  vue-native-scripts

### ISSUE THREAD

**Issue by vahidalvandi** [GeekyAnts/vue-native-core#155]
Loading dependency graph, done.
(node:8724) UnhandledPromiseRejectionWarning: Error: Cannot find module 'vue-native-scripts'

you must add vue-native-script in dependencies
```
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59",
    "vue-native-core": "0.0.8",
    "vue-native-helper": "0.0.11"
  }
```

**Comment by tjimenez** [comment]
Same for me!

**Comment by icarter09** [comment]
@vahidalvandi are you still experiencing this issue?

**Comment by anoop-ananthan** [comment]
Same issue for me...
Tried : `npm install vue-native-scripts --save-dev`
Result:
```
anoop@lenovo-pc:~/coding/learn/vue-native/sample$ npm install vue-native-scripts --save-dev
npm WARN vue-native-scripts@0.1.0 requires a peer of metro-bundler@* but none is installed. You must install peer dependencies yourself.
```

**Comment by RishabhKarnad** [comment]
@vahidalvandi as mentioned by @anoop-ananthan `vue-native-scripts` is a devDependency and should be installed automatically by `vue-native-cli` during project.

This should not be an issue in the latest releases. Please reopen this ticket if it is still an issue.

**Comment by mk6488** [comment]
> This was an issue for me as well, fresh install of vue-native-cli.
> Fixed it with solution above.

Same issue here. What solution?
