### ISSUE TITLE
Convert Reactnative Project to Vue.js

### ISSUE THREAD

**Issue by mahipalsingh7** [GeekyAnts/vue-native-core#159]
anyone please help me how can i convert the existing ReactNative Project to Vue.js ?

**Comment by icarter09** [comment]
@mahipalsingh7 were you able to come up with a solution?

**Comment by RishabhKarnad** [comment]
@mahipalsingh7 If you wish to use Vue Native inside a React Native project, it is possible to do so. Follow the instructions given [here](https://github.com/GeekyAnts/vue-native-core/blob/master/converting-react-native-project.md). This will allow you to create new Vue single file components and import React Native components you have created inside them, and allow `.js` and `.vue` files to co-exist in your project.

At the moment, Vue Native does not provide a way to convert React code into Vue, and we probably won't add it in the future.
