### ISSUE TITLE
render-prop-fn broken

### ISSUE THREAD

**Issue by rothskeller** [GeekyAnts/vue-native-core#160]
It appears that references to arguments of a prop function are not working.  My code tracks exactly with the example on the vue-native web site:

```
    <flat-list :data="events">
      <view render-prop-fn="renderItem">
        <text>{{ args.item.name }}</text>
      </view>
    </flat-list>
```

but it results in an error:

```
console.error: "[Vue warn]: Property or method "args" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
```

Am I doing something wrong, or is it really broken?  Help would be much appreciated.

**Comment by icarter09** [comment]
@rothskeller did you have any luck in feedback on this issue or find a solution?

**Comment by rothskeller** [comment]
@icarter09 I did not find a solution, but I worked around the problem, so it is no longer blocking me.

**Comment by icarter09** [comment]
@rothskeller glad to hear it. Do you think this issue can be closed or should be left open?

**Comment by rothskeller** [comment]
Probably best to close it, without prejudice, until/unless someone else hits it.  I'm no longer in a position to help test a fix.
