### ISSUE TITLE
Has the project stopped?

### ISSUE THREAD

**Issue by publicaccount365** [GeekyAnts/vue-native-core#162]
Hi
Has the project stopped?
please update because this is great project.

**Comment by LiveDuo** [comment]
It would be interesting to know if there are any active contributors to the
projects?

**Comment by GaraGentor** [comment]
I also hope, that this project hasn't stopped.

**Comment by madhavarshney** [comment]
There's also [NativeScript-Vue](https://nativescript-vue.org/), which serves a similar purpose.

**Comment by sanketsahusoft** [comment]
We are continuing to maintain Vue Native. You will see a lot of updates in the coming days.
