### ISSUE TITLE
componentWillMount, componentWillReceiveProps and componentWillUpdate are deprecated in React 16.8.6, React Native 0.60.0

### ISSUE THREAD

**Issue by RohanTalip** [GeekyAnts/vue-native-core#166]
In Xcode with Vue Native and React 16.8.6 / React Native 0.60.0 (i.e. up-to-date versions), I see the following warnings:
```
Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.

Please update the following components: ReactVueComponent

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

```
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: ReactVueComponent

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

```
Warning: componentWillUpdate is deprecated and will be removed in the next major version. Use componentDidUpdate instead. As a temporary workaround, you can rename to UNSAFE_componentWillUpdate.

Please update the following components: ReactVueComponent

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

**Comment by RohanTalip** [comment]
It looks like this was reported last year in the NativeBase repository with React Native v0.54.0 : https://github.com/GeekyAnts/NativeBase/issues/1665

So, I'm not sure of the priority 😃

**Comment by icarter09** [comment]
@RohanTalip are you still seeing the warning messages? The only one I have come across is for 'ImageStore'. I believe the reason for the deprecation is React replacing these functions with the new Hooks.

**Comment by RohanTalip** [comment]
> @RohanTalip are you still seeing the warning messages? The only one I have come across is for 'ImageStore'. I believe the reason for the deprecation is React replacing these functions with the new Hooks.

@icarter09, I was still seeing the warning messages this morning.  After upgrading vue-native-{core,helper,scripts} to version 0.1.0, I am no longer seeing these warning messages for `ReactVueComponent`.

Thanks, @gauravprwl14!
