### ISSUE TITLE
Unable to setup Vuenative with react-native version (0.60.0)

### ISSUE THREAD

**Issue by devarashetty** [GeekyAnts/vue-native-core#170]
I am facing the error 
`unable to resolve module App.vue`  under `index.js` file even though I can see the import being done properly .

I checkted `vueTransformPlugin.js`  file where we are trying to import `metro/src/transformer` which is not available under npmmodule `metro`.

**Comment by icarter09** [comment]
@devarashetty can you list the steps for how to recreate this issue? Thanks.

**Comment by melvinchng** [comment]
I am also facing the same issue, but with React Native 0.60.5

`unable to resolve module App.vue` under `index.js`

I followed the steps here: https://vue-native.io/docs/installation.html#Setup-with-React-Native

**Comment by melvinchng** [comment]
I faced the same issue. When creating a new project, I follow this documentation: https://vue-native.io/docs/installation.html#Setup-with-React-Native

I skipped step 3 and follow the instructions here: https://www.npmjs.com/package/vue-native-scripts

**Comment by RishabhKarnad** [comment]
@devarashetty @melvinchng The documentation has been updated. Please reopen this ticket if you face an issue even after following the new steps.
