### ISSUE TITLE
How to access CSS classes in style tag?

### ISSUE THREAD

**Issue by tmaly1980** [GeekyAnts/vue-native-core#174]
Is there a way to declare a class within the <style> block but reference it within the template as a value for a style attribute? For example:

```
<template>
  <text :style="[$styles.class1, $styles.class2]">Colored Text</text>
</template>
<style>
.class1 {
  background-color: red;
}
.class2 {
  color: white;
}
</style>
```

I like being able to declare plain CSS but I sometimes need to combine multiple styles depending on the content. I'd much rather keep to declaring CSS within the style block rather than having to write JS styling. 

Is the parsed stylesheet available as a variable?

**Comment by RishabhKarnad** [comment]
Hi @tmaly1980. Would using multiple class names with `class` work for you?

You could do something like this:
```
<text class="class1 class2">Colored text</text>
```

**Comment by RishabhKarnad** [comment]
Closing this issue for now. @tmaly1980 please reopen it if you face an issue with this solution, or if you think it does not solve your particular problem
