### ISSUE TITLE
Input text and switch issue

### ISSUE THREAD

**Issue by mariomka** [GeekyAnts/vue-native-core#18]
There is a problem when input text has been binded to a model, the text is repeating. And switches back to original position automatically.

![input-switch-issue](https://user-images.githubusercontent.com/1822472/41383563-abbf4962-6f71-11e8-89be-68b196ef880b.gif)

Device: BQ Aquaris M5.5 - Android 6.0.1

Start new project (rn or crna) and replace App.vue with the following code:

```vue
<template>
  <view class="container">
    <text>With model:</text>
    <text-input
        class="input"
        v-model="message"
    />
    <text>Without model:</text>
    <text-input
        class="input"
    />
    <text>Switch:</text>
    <switch
        :on-value-change="handleChange"
        :value="value" />
  </view>
</template>


<script>
export default {
  data () {
    return {
      message: 'Test',
      value: true
    }
  },

  methods: {
    handleChange: () => {
      this.value = !this.value
    }
  }
}
</script>

<style>
.container {
  background-color: white;
  align-items: center;
  justify-content: center;
  flex: 1;
}

.input {
  width: 100%;
}
</style>
```

**Comment by mariomka** [comment]
Same switch issue in iphone simulator but input text is working fine.

**Comment by ormedo** [comment]
ON asus zendphone 3 android 8 same issue.

**Comment by mariomka** [comment]
@gauravprwl14 thank you! The input text is working fine on the latest version 0.0.6 but switch issue hasn't been resolved.

**Comment by neeraj-singh47** [comment]
@mariomka V-model will not work in switch. You'll have to map the props according to React Native docs

**Comment by mariomka** [comment]
Code from docs isn't working (https://vue-native.io/docs/basic-components.html#Switch).

Following the react-native docs don't help:

```vue
<template>
  <view class="container">
    <switch
        :onValueChange="handleChange"
        :value="value" />
  </view>
</template>


<script>
export default {
  data () {
    return {
      value: true
    }
  },

  methods: {
    handleChange: value => {
      console.log(value) // false
      this.value = value
    }
  }
}
</script>

<style>
.container {
  background-color: white;
  align-items: center;
  justify-content: center;
  flex: 1;
}
</style>
```

Tested on android device and iOS simulator.

**Comment by neeraj-singh47** [comment]
@mariomka Seems like the issue is because of the onChange format. Can you try `handleChange(val) {
       this.test = val
 }`

**Comment by mariomka** [comment]
@neeraj-singh47 thank you, you are right, Vue can't define `this` with arrow functions... The syntax is so similar...

**Comment by anson-GH** [comment]
Thanks. It work for me

```
<template>
    <view style = {style.container}>
        <switch
            :on-value-change = "handleChange"
            :value = "value"/>
    </view>

</template>
<script>
    export default {
        data: function() {
            return {
                value: false
            }
        },
        methods: {
            handleChange(val){
                this.value = val
            }
        }
    }
</script>
```
