### ISSUE TITLE
ENOENT: no such file or directory, chmod '...\node_modules\vue-native-scripts\src\bin\vue-native-script.js'

### ISSUE THREAD

**Issue by zyxel648** [GeekyAnts/vue-native-core#182]
Trying to Install last version 0.1.0
`npm install vue-native-scripts@0.1.0`

but get following error in console:
```
npm ERR! path C:\sample\node_modules\vue-native-scripts\src\bin\vue-native-script.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\sample\node_modules\vue-native-scripts\src\bin\vue-native-script.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```
and package did not installed

I suppose, this is cause in package.json wrong path to vue-native-script.js file:
```
"bin": {
    "vue-native-scripts": "./src/bin/vue-native-script.js"
  },
```
It should be:
```
"bin": {
    "vue-native-scripts": "./bin/vue-native-script.js"
  },
```

**Comment by zyxel648** [comment]
Use `yarn install` to solve this issue

**Comment by XavierOlland** [comment]
"It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files."

I'm sorry but "install with yarn" is not an answer when all the docs point to npm.

**Comment by zyxel648** [comment]
Ok. But I'm not owner of package and this is only my solution. 
Reopen issue, maybe someday it will by fixed 🤷‍♂️

**Comment by XavierOlland** [comment]
Yes that's what I meant, It need a proper fix and shouldn't be closed

**Comment by TranVanThaiSon** [comment]
and end what solve that?

**Comment by TranVanThaiSon** [comment]
This is my solve: add code in package.js
` "devDependencies": {
    "@babel/core": "7.5.5",
    "@babel/runtime": "7.5.5",
    "babel-jest": "24.8.0",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.56.0",
    "react-test-renderer": "16.8.3",
    **### "vue-native-scripts": "0.0.16"**
  },`

**Comment by envisean** [comment]
I believe @RishabhKarnad has just patched it and will be releasing a fix soon. Check https://github.com/GeekyAnts/vue-native-core/issues/191
