### ISSUE TITLE
Can we use other UI framework?

### ISSUE THREAD

**Issue by alighasemzadeh** [GeekyAnts/vue-native-core#188]
Hello,
Can I use other UI framework to build application?

**Comment by RohanTalip** [comment]
Hi @alighasemzadeh, yes, you can.  I'm currently using a mix of the [Vue Native basic components](https://vue-native.io/docs/basic-components.html) (which are really just wrappers around [React Native components](https://facebook.github.io/react-native/docs/components-and-apis.html)), [Native Base](https://nativebase.io/) components, components from [React Native Elements](https://react-native-training.github.io/react-native-elements/) and other individual components.

So far, I have found that anything that can be used in React Native can also be used with Vue Native, although usually with some translation of the syntax into what Vue / Vue Native expects.

**Comment by alighasemzadeh** [comment]
@RohanTalip 
Thanke for your answer.
I want to use Vuetify for my UI and for device api use vue-native.
Can you guide me how to do this job?

**Comment by RohanTalip** [comment]
@alighasemzadeh, you're welcome.

> I want to use Vuetify for my UI and for device api use vue-native.

I'm assuming that you want to use Vuetify for your website / web app.  I don't see any problem with that.  I suspect you will need to have 2 source trees for each app (although you will likely have similar code shared or copied between them).

> For example using expo for device api
> Can you guide me how to do this job?

I am not using expo, but there appear to be other people using it with Vue Native.

You could start by looking at the [documentation for device APIs](https://vue-native.io/docs/device-apis.html) or search for what you want on your favourite search engine or join the [Vue Native Slack community](http://slack.vue-native.io) and ask your question there.

Good luck!

**Comment by sanketsahusoft** [comment]
You're doing a great job @RohanTalip. Loads of love ❤️ from the Vue Native Team at GeekyAnts

**Comment by Syltis** [comment]
Hi! I'm trying to use [Material Design](https://vuematerial.io/getting-started) with Vue Native, but I' getting an error when trying to import and Vue.use(MdMenu):

`Unable to resolve module 'vue' from ../source/repos/vuenativetester/node-modules/vue-material/dist/components/MdMenu/index.js' Module 'vue' does not exist in the Haste module map
`

Any experience on this?

**Comment by RohanTalip** [comment]
Hi @Syltis,

First of all, the [Vue Material](https://vuematerial.io/) project that you linked to provides web UI components, which won't make sense in a Vue Native / React Native mobile development environment (unless you're using the web UI components in a [WebView](https://github.com/react-native-community/react-native-webview)).

Secondly, Vue Native started with a Vue.js core but modified it to act as a bridge between [Vue Single File Components](https://vuejs.org/v2/guide/single-file-components.html) (SFCs) and React Native libraries (actually, the SFCs are translated into React Native code).  As a result, in a Vue Native project, by default you will no longer import Vue from "vue" but instead from "vue-native-core", and the "vue" module will not be available in your node_modules directory (unless you add it yourself).

To find Material Design libraries or components that will work with Vue Native, I recommend searching for "react native material design" (or similar) on your favourite search engine.

Some libraries/packages I have come across (but don't yet have experience with) include:

- [React Native Paper](https://reactnativepaper.com/)
- [React Native Material UI](https://github.com/xotahal/react-native-material-ui)
- [React Native Material Kit](http://xinthink.github.io/react-native-material-kit/)

There may be others ...

**Comment by alighasemzadeh** [comment]
@RohanTalip 
Hello,
It looks we can not use web UI for native environment.

**Comment by RishabhKarnad** [comment]
To summarise, it is possible to use components from React Native component libraries by importing and then declaring them as a child component int the `<script>` part of your `.vue` SFC.

```html
<template>
    <view>
        <!-- notice the kebab-case, although you can use PascalCase as well -->
        <some-ui-component />
    </view>
</template>

<script>
// Import the same way as you would in a JS file
import { SomeUiComponent } from 'a-ui-library'

export default {
    components: {
        // Declare the component here. It can't be used otherwise
        SomeUiComponent,
    },
    /* data, props, methods, etc */
}
</script>
```

Components provided by `react-native` itself, like View and Text can be used without the need to import.

However, it is *not* possible to directly use web UI library components, including libraries designed for Vue.js.

**Comment by obitux** [comment]
What about the dot notation in react native ui libs as Paper ? Can't figure out how to import and use those components ...

**Comment by RishabhKarnad** [comment]
@obitux this should work:

```
<appbar:action icon="archive" :on-press="() => { console.log('something') }" />
```

**Comment by jawahar273** [comment]
Please Include the about example in documentation to others. @RishabhKarnad
