### ISSUE TITLE
Vuex store or plugins generally

### ISSUE THREAD

**Issue by joshua1** [GeekyAnts/vue-native-core#2]
Hi ,
I am currently playing around with this set of projects (using the CLI tool) . i wish to know how to use vuex store with this given that there is no new Vue instance that takes a store property or any other custom plugin for that matter that needs to be injected into the global vue object instance as a prototype or property. I tried creating a store plugin like in boot/setup.vue
```
Vue.use(VueNativeBase)
const store = createStore()
Vue.use(Vuex)
const storePlugin = {
  install(Vue, options) {
    Vue.prototype.$store = store
  },
}
Vue.use(storePlugin)
```
but i get an errror that states 
```undefined is not an object (evaluating plugin.installed) ```

**Comment by neeraj-singh47** [comment]
@atilacamurca has already provided the solution which is a recommended to use plugins

**Comment by fergardi** [comment]
Im still uncertain about this procedure. Usually when I need to add a new library I npm-install --save it, and then import it in my main.js. Where is the access point in the vue-native app?

**Comment by atilacamurca** [comment]
According to <https://vue-native.io/docs/installation.html> at the **Step 4 Create A Vue File** section,
the main entry point is a SFC (`.vue` file) at the root of your project. You do not need to manually mount the root component.

**Comment by aaronksaunders** [comment]
@fergardi @atilacamurca i found it easier to just do this in `App.vue`
```
  Vue.prototype.$store = store;
```
otherwise you cannot use any of the vuex helpers `mapGetters` or `mapActions`

**Comment by fergardi** [comment]
Thank you.
