### ISSUE TITLE
Status-bar doesn't paint anything

### ISSUE THREAD

**Issue by ormedo** [GeekyAnts/vue-native-core#20]
HI!

Im testing basic react components and status bar does not work as expect.

Just install a new instalation and change <template> with this:

<template>
  <view class="container">
    <status-bar
        background-color="blue"
        bar-style="light-content"
      />
    <view>
      <text>Hellow Word With status-bar</text>
    </view>
  </view>
</template>

**Comment by sanketsahusoft** [comment]
Can you provide some code to reproduce the bug?

**Comment by windyflying** [comment]
@ormedo I guess you made a spelling mistake on the word `anithing`.
It seems to be anything

**Comment by ormedo** [comment]
Just make a clean install and try de docs code

```
<view>
        <status-bar
            background-color="blue"
            bar-style="light-content"
        />
</view>
```

The result its a empty white page.
Attach image of iOS simulator

<img width="368" alt="captura de pantalla 2018-06-18 a las 9 12 03" src="https://user-images.githubusercontent.com/23084038/41522740-af68bc1a-72d7-11e8-8022-ff89f1f3a44b.png">

**Comment by neeraj-singh47** [comment]
@ormedo Currently you cannot set background color for ios through StatusBar. But there is a different way to implement that. You can see a example here https://stackoverflow.com/questions/39297291/how-to-set-ios-status-bar-background-color-in-react-native

**Comment by ormedo** [comment]
OK, on iOS have sense.
But on Android I got the same result, here the screenshot of Expo with the same code on asus Zendfone 3 with Android 8.0.

![screenshot_20180618-101951](https://user-images.githubusercontent.com/23084038/41525446-501898a2-72e1-11e8-91c0-03233b2b55f0.jpg)
