### ISSUE TITLE
Aliases for dirs

### ISSUE THREAD

**Issue by s3bul** [GeekyAnts/vue-native-core#204]
Can configure and use aliases? I mean https://webpack.js.org/configuration/resolve/

**Comment by s3bul** [comment]
Ok, i found this https://github.com/janaagaard75/expo-and-typescript/issues/21#issuecomment-499459446 and working.

**Comment by RishabhKarnad** [comment]
@s3bul you could use `babel-plugin-module-resolver` for this

https://github.com/tleunen/babel-plugin-module-resolver/blob/master/DOCS.md

It would involve installing the plugin and changing the `.babelrc` in your project

**Comment by s3bul** [comment]
It's only working when i use alias in App.vue, in other files, like `src/Setup.vue` when i import `src/screens/Login` i got error like
`transform[stderr]: Could not resolve "src/screens/Logo" in file src/Setup.vue`

Maybe the problem is docker container, but i write more projects with docker and aliases in webpack, and there isn't any problems.

**Comment by s3bul** [comment]
> It's only working when i use alias in App.vue, in other files, like `src/Setup.vue` when i import `src/screens/Login` i got error like
> `transform[stderr]: Could not resolve "src/screens/Logo" in file src/Setup.vue`
> 
> Maybe the problem is docker container, but i write more projects with docker and aliases in webpack, and there isn't any problems.

Ok, i did some things and its working now

**Comment by RishabhKarnad** [comment]
@s3bul You could share your solution here as it would help others who might have similar issues.

**Comment by s3bul** [comment]
I add `extensions` for plugin
```js
extensions: [
    '.js',
    '.vue',
],
```
and i changed name for `axios.js` file (i creating there my axios instance), because i got error like "axios file import self" in line `import axios from 'axios'`. Next i created `webpack.config.js` file, where i set only aliases and i import this file in `babel.config.js`.
File `webpack.config.js` is only for phpstorm webpack settings.
