### ISSUE TITLE
Vue native executes App.js instead of App.vue

### ISSUE THREAD

**Issue by YannickSilva** [GeekyAnts/vue-native-core#205]
Hey i'm having a problem i want to start learning vue native but when i execute he always starts app.js instead of app.vue.How do i solve this problem, i really need help with that

**Comment by RishabhKarnad** [comment]
@YannickSilva it would help if you provided the following info:
- What platform are you using (OS an shell)?
- Did you create the project using `vue native-cli` or did you convert a React Native project?
- Also, are you using Expo as the basis or just bare React Native?

Could you also share the list of files in your project directory (maybe the result of running `ls` at the project root?)

**Comment by YannickSilva** [comment]
I'm using Windows 10 with the command line, i created the project using vue native-cli and i use Expo as the basis and still he keeps running App.js instead of App.vue i'm so frustated.

**Comment by RishabhKarnad** [comment]
Could you share the directory structure that was generated?

**Comment by YannickSilva** [comment]
![ScreenShot_20190916195017](https://user-images.githubusercontent.com/25250749/64984735-4f27c080-d8bb-11e9-9884-ff240a15abfb.png)

**Comment by RishabhKarnad** [comment]
Confirmed that this is an issue on Windows. The App.js file is not being deleted after the App.vue file has been created. This will be fixed with the next release.

**Comment by RishabhKarnad** [comment]
Closing this issue as a new one has been opened in https://github.com/GeekyAnts/vue-native-cli instead, as it would be more relevant to that repo.

https://github.com/GeekyAnts/vue-native-cli/issues/29

**Comment by YannickSilva** [comment]
@RishabhKarnad  when is the next release coming ?

**Comment by RishabhKarnad** [comment]
@YannickSilva The next release of Vue Native CLI should be out within the next two weeks. Until then, please add any comments on the relevant issue in that repo. All updates related to this issue will be posted there.

**Comment by kothanzaw** [comment]
still not solve. ? 

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~37.0.3",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-web": "~0.11.7",
    "vue-native-core": "^0.1.4",
    "vue-native-helper": "^0.1.4"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0",
    "vue-native-scripts": "^0.1.4"
  },
  "private": true
}
on window 10

**Comment by simon-caceres** [comment]
today i´m having the same problem, did someone could fix it?

**Comment by RishabhKarnad** [comment]
This issue has been fixed.

https://github.com/GeekyAnts/vue-native-cli/releases/tag/v0.1.2
