### ISSUE TITLE
vue-native without expo

### ISSUE THREAD

**Issue by alighasemzadeh** [GeekyAnts/vue-native-core#207]
Hello,
Is it possible to use vue-native without expo?

**Comment by RishabhKarnad** [comment]
Yes, when creating the project, just use the `--no-expo` option.

Installation is described in detail [here](https://vue-native.io/docs/installation.html)

**Comment by alighasemzadeh** [comment]
@RishabhKarnad 
I need Device APIs, Is it possible?

**Comment by RishabhKarnad** [comment]
@alighasemzadeh apologies that this reply took so long. We'll update the docs soon to show examples of device APIs without Expo.

**Comment by MuizU** [comment]
I do not have a start script when I use --no-expo

**Comment by RishabhKarnad** [comment]
@MuizU what OS are you using?

**Comment by MuizU** [comment]
Endeavour is with deepin dde
