### ISSUE TITLE
Destroy component after navigating to other

### ISSUE THREAD

**Issue by s3bul** [GeekyAnts/vue-native-core#210]
Why components dont destroy after i going to other? Or I do something wrong?

**Comment by envisean** [comment]
It shouldn't get destroyed. If you're using the vue-native-router, then it's navigating and should be kept alive.

This is more of a behavior of react-navigation

**Comment by s3bul** [comment]
So how can I force destroy? Or how I can catch "mount" screen event or something similar? In vue `created` and `mounted` it's important thing.

**Comment by net8floz** [comment]
What's also interesting is that using the .navigate function will cause screens to always call created() but I have yet to have it call destroyed() . Does it sound like I'm misusing the router? If not I would expect some kind of cleanup event to be accessible =D

**Comment by ChrisKader** [comment]
@net8floz: unmountInactiveRoutes: true

Components are recycled. You aren’t really creating a new one every time. That prop will force you to though.

**Comment by ChrisKader** [comment]
https://reactnavigation.org/docs/en/navigation-lifecycle.html

**Comment by RishabhKarnad** [comment]
@s3bul in case you wish to do this with a drawer navigator, you can use `unmountInactiveRoutes` in the navigator's config:

https://reactnavigation.org/docs/en/drawer-navigator.html#drawernavigatorconfig

**Comment by ido-aim** [comment]
Extra note here:

after added `unmountInactiveRoutes:true` in `createDrawerNavigator()`, the unmount event would fire using `beforeDestroy` hook. This obviously worked with screen registered in `createDrawerNavigator()`
