### ISSUE TITLE
trying to use vue-i18n 

### ISSUE THREAD

**Issue by francoisp** [GeekyAnts/vue-native-core#216]
Tried to use vue-i18n with vue-native-core, and when attempting use with 

``` 
Vue.use(VueI18n);
```
I get this warning: [vue-i18n] vue-i18n (undefined) need to use Vue 2.0 or later (Vue: 0.1.4). Then when using $t() I get this error: [Vue warn]: Property or method "$t" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

**Comment by RishabhKarnad** [comment]
@francoisp This happens because the version of the `Vue` export from `vue-native-core` is generated from the package version, which at this point would be `0.1.4`

We'll change this version number to the Vue.js version we forked from, in the next release. Since the version was `^2.0.0`, the issue should be fixed then.

**Comment by francoisp** [comment]
ok awesome! Where would I edit this to test locally? 

FWIW I've also come across vuex-i18n, that one works with vue-native-core (also it uses vuex for lazy loading), but the rest of my stuff uses nuxt-i18n and that leverages vue-i18n... I'd like to use the same format for i18n in native and web artifact... At first glance vuex-i18n looks leaner and more flexible, but nuxt-i18n nails it for SSR as well as apps.

**Comment by RishabhKarnad** [comment]
You could edit build.js in the vue-native-core node module. There should be
a line similar to

```
Vue.version = '0.1.4';
```

Line 3863 in the latest release.

We haven't tested the other libraries you mentioned yet, although they
should work fine if they are independent of browser APIs.

**Comment by francoisp** [comment]
thanks for the quick answer! I tried updating the Vue.version in the build file, but now I get  
```
TypeError: undefined is not an object (evaluating 'i18n._t') 
```
vue-i18n seems a bit more integrated; I'm thinking I might just stick to translations in a json format instead of the fancy promise alternative that vue-i18n and nuxt-i18n offer; that way the same json files can be used for vuex-i18n...

**Comment by alexrok21** [comment]
excuse me, could someone integrate i18n to an a vue-native project? thanks

**Comment by doubleh311** [comment]
> 
> 
> excuse me, could someone integrate i18n to an a vue-native project? thanks

I am using i18n-js for my vue-native_expo project and it could work as expectation. You can try it

**Comment by silianpan** [comment]
_**Vue.prototype._i18n = i18n**_ must be under the line _**App.mpType = 'app'**_
```js
App.mpType = 'app'
Vue.prototype._i18n = i18n
```

**Comment by UsamaAltaf** [comment]
@doubleh311 How to use i18n-js in Vue Native project I can't be able to use i18n.t('')
