### ISSUE TITLE
Vue native to Vue PWA conversion

### ISSUE THREAD

**Issue by adarshsosale** [GeekyAnts/vue-native-core#226]
I'm looking to write a VueJS PWA with a NodeJS backend. I will have to convert the app into a native iOS one afterwards. Are there any tools to automate the conversion process? How do I go about it?

Thank you!

**Comment by RishabhKarnad** [comment]
Vue Native does not provide any ways to automate conversion from PWAs/responsive web apps into native apps, and as of now there are no plans to support this. Closing this issue for this reason. Please feel free to discuss this on Vue Native Slack.
