### ISSUE TITLE
Cannot blur my images

### ISSUE THREAD

**Issue by maxencedouet** [GeekyAnts/vue-native-core#229]
I would like to blur my image so use the blurRadius available in the image react component, I type it 
`<image blurRadius="{3}"/>`
it work well on ios but raises an error in android (an error in the terminal 3 should be an integer).
I tried serveral possibilities such as `:blurRadius="{3}"` but didn't find any way around
Any idea of how to solves this ?

**Comment by RishabhKarnad** [comment]
Hey @maxencedouet have you tried `:blurRadius="3"`? That would be the correct syntax.

**Comment by maxencedouet** [comment]
Yes, you are right, thank you very much !!
