### ISSUE TITLE
Create a global stylesheet?

### ISSUE THREAD

**Issue by thegeminisociety** [GeekyAnts/vue-native-core#23]
Is there a good method for creating a global stylesheet that all Vue components could have access to?

**Comment by smithb1994** [comment]
See the [Vue docs](https://vuejs.org/v2/guide/), don't raise the issue here. Normally you put it in App.vue.

**Comment by sanketsahusoft** [comment]
That is something which I wouldn't recommend because global style creates more harm than good. A better way of doing it would be composing components instead of global style. Like having a Design system of Components consuming a theme variable file.

**Comment by thegeminisociety** [comment]
You are correct, closing the issue
