### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by maxencedouet** [GeekyAnts/vue-native-core#230]
I don't manage to make apple-authentication working (compulsory to publish on apple store). Cf: https://docs.expo.io/versions/latest/sdk/apple-authentication/

Do you know any workaround ? 

Thank you very much for your help

Kind regards, 

Maxence

**Comment by RishabhKarnad** [comment]
What issues are you facing?

**Comment by maxencedouet** [comment]
RishabhKarnad , thank you for you response. I did manage to find out what was bugging. I close the issue.

**Comment by RishabhKarnad** [comment]
Thanks @maxencedouet. In case you think it is a common issue you could post the solution here, in case someone else runs into it
