### ISSUE TITLE
Question: hi GeekyAnts i need your help

### ISSUE THREAD

**Issue by lavy1004** [GeekyAnts/vue-native-core#232]
The best place to find answers is the [documentation](https://www.vue-native.io/docs/installation.html)  📖

If you still haven't found what you are looking for or need more help, feel free to reach out on [Vue Native Slack](http://slack.vue-native.io/)

now i make the vue native app 

but how to use chart.js vue-native 

i remember run the chart.js in vue.js port 8080... but  Vue-native.. i dont know 

i really hope you read this questions .. thanks you ..

**Comment by RishabhKarnad** [comment]
chart.js is not compatible with Vue Native or React Native. Please use [react-native-chart-kit](https://www.npmjs.com/package/react-native-chart-kit) or [react-native-svg-charts](https://www.npmjs.com/package/react-native-svg-charts)
