### ISSUE TITLE
Vue Native Scripts API doesn't cover reactVueTemplateParser anymore for testing components

### ISSUE THREAD

**Issue by Recursif** [GeekyAnts/vue-native-core#236]
I want to setup the test environment on our vue-native mobile application but I face some issues.

In the documentation of vue-native, in the testing section, it's written "Parse the data using vue-native-scripts‘ reactVueTemplateParser function to extract elements from the vue code." (Cf: [https://vue-native.io/docs/testing.html]).

But when I look inside the vue-native-scripts there only two functions:
```
{
  compileVueToRn: [Function: compileVueToRn],
  transform: [Function: transform]
}
```
So it's seems that the vue-native-scripts Api has changed :s

The problem is that none of those 2 functions above are documented, so I don't now how I can perform this transformation from vue-native to react-native component.

Here, the version of vue-native I used:
```
"vue-native-core": "0.1.4",
"vue-native-helper": "0.1.4",
"vue-native-scripts": "^0.1.4"
```

Thank you in advance for your help ;)

**Comment by RishabhKarnad** [comment]
Hi @Recursif the docs are a bit outdated right now and we're working to keep them up to date. You can use `compileVueToRn` instead for snapshot testing

**Comment by Recursif** [comment]
Thank you @RishabhKarnad I'll try this way!

**Comment by RishabhKarnad** [comment]
@Recursif feel free to reopen if this approach causes issues
