### ISSUE TITLE
Question: vue-native-scripts having issues?

### ISSUE THREAD

**Issue by Mgrmjp** [GeekyAnts/vue-native-core#238]
> warning " > vue-native-scripts@0.1.4" has incorrect peer dependency "react-native@^0.59.0".
warning " > vue-native-scripts@0.1.4" has unmet peer dependency "metro@^0.51.0".
warning " > vue-native-scripts@0.1.4" has unmet peer dependency "metro-bundler@*".
warning " > vue-native-scripts@0.1.4" has unmet peer dependency "metro-react-native-babel-transformer@^0.51.0".

Trying to install packages in my Vue Native projects and I'm not sure how to proceed with this information.

**Comment by RishabhKarnad** [comment]
Hi @Mgrmjp this shouldn't cause any issues while running the app. We'll try to fix these in the next release.

Please let us know in case this is causing any issues running the app.

**Comment by Mgrmjp** [comment]
I don't know if it is, but vue-native-router MaterialTopTabNavigator swipe motions are causing the whole app to crash. I suppose this has nothing to do with it?

**Comment by RishabhKarnad** [comment]
@Mgrmjp Could you provide any error messages that you are seeing?

**Comment by Mgrmjp** [comment]
> \[Unhandled promise rejection: TypeError: subs is not a function. (In 'subs(payloadWithType)', 'subs' is undefined)]
\- node_modules\@react-navigation\core\lib\module\getChildEventSubscriber.js:57:4 in emit
\* [native code]:null in forEach
\- node_modules\@react-navigation\core\lib\module\getChildEventSubscriber.js:56:24 in emit
\- node_modules\@react-navigation\core\lib\module\getChildEventSubscriber.js:109:10 in addListener$argument_1
\- node_modules\@react-navigation\core\lib\module\getChildEventSubscriber.js:57:4 in emit
\* [native code]:null in forEach
\- node_modules\@react-navigation\core\lib\module\getChildEventSubscriber.js:56:24 in emit
\- node_modules\@react-navigation\core\lib\module\getChildEventSubscriber.js:111:13 in addListener$argument_1
\- node_modules\@react-navigation\native\lib\module\createAppContainer.js:314:41 in dispatchActions
\* [native code]:null in forEach
\- node_modules\@react-navigation\native\lib\module\createAppContainer.js:314:30 in dispatchActions
\* http://192.168.1.39:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:135583:34 in componentDidMount$
\- node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
\- node_modules\regenerator-runtime\runtime.js:274:30 in invoke
\- node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
\- node_modules\regenerator-runtime\runtime.js:135:28 in invoke
\- node_modules\regenerator-runtime\runtime.js:145:19 in PromiseImpl.resolve.then$argument_0
\- node_modules\promise\setimmediate\core.js:37:14 in tryCallOne
\- node_modules\promise\setimmediate\core.js:123:25 in setImmediate$argument_0
\- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:146:14 in _callTimer
\- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:194:17 in _callImmediatesPass
\- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:458:30 in callImmediates
\* [native code]:null in callImmediates
\- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:407:6 in __callImmediates
\- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:143:6 in __guard$argument_0
\- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10 in __guard
\- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:142:17 in __guard$argument_0
\* [native code]:null in flushedQueue
\* [native code]:null in invokeCallbackAndReturnFlushedQueue

This one pops up in my own project when the app loads and then crashes once you try to navigate by swiping. I didn't get an error when I ran the example for vue-native-router, but Expo crashed.

**Comment by Mgrmjp** [comment]
My errors had to do with ⬇

>   this.focusListener = navigation.addListener("didFocus", () => {
      // The screen is focused
      // Call any action
    });

I had removed the function from the listener and it was causing nav to blow up.
