### ISSUE TITLE
Persist data with vuex and vuex-persistedstate

### ISSUE THREAD

**Issue by jechazelle** [GeekyAnts/vue-native-core#242]
Hello, 👋

I would like to use vuex-persistedstate (more recent and more stars) and no use vuex-persiste ([example](https://github.com/GeekyAnts/vue-native-starter-app/blob/feat/dataPersistence/src/store/index.js))

The store runs, but I have an error when I use vuex-persistedstate :

    import Vue from 'vue-native-core'
    import Vuex from 'vuex'
    import createPersistedState from 'vuex-persistedstate'
    
    import { chat } from '../modules/chat/store/chatStore'
    
    Vue.use(Vuex)
    
    export default new Vuex.Store({
        // Modules
        modules: {
            chat
        },
    
        plugins: [ createPersistedState() ]
        
    })

I try with this, but I have the same error :

    plugins: [
        createPersistedState({
            paths: ['chat'],
        }),
    ],

**undefined is not an object (evaluating 'e.setIem')**

[![enter image description here][1]][1]

I import AsyncStorage to use it :

    import { AsyncStorage } from "react-native";

and config the createPersistedState object

    plugins: [ createPersistedState({ storage : AsyncStorage}) ]

but I have an other error :

[![enter image description here][2]][2]

Do you have an idea, how can I use vuex-persistedstate with vue-native-core please ?
Thank you !

  [1]: https://i.stack.imgur.com/f6N9R.png
  [2]: https://i.stack.imgur.com/aWLm6.png

**Comment by xnextx** [comment]
+1

**Comment by RishabhKarnad** [comment]
@jechazelle it's possible to define `setItem`, `getItem` and `removeItem` like this

```
createPersistedState({
  storage: {
    getItem: (key) => Cookies.get(key),
    // Please see https://github.com/js-cookie/js-cookie#json, on how to handle JSON.
    setItem: (key, value) =>
      Cookies.set(key, value, { expires: 3, secure: true }),
    removeItem: (key) => Cookies.remove(key),
  },
}),
```

Could you try defining them using `AsyncStorage` according to your use case?

**Comment by xnextx** [comment]
@jechazelle @RishabhKarnad Hey, I did. AsyncStorage is, as the name suggests, asynchronous. vuex-persistedstate does not support asynchronous data. You can use "getItem" "setItem" etc. and everything works, but you have to remember that vue instance should only run when all promises are finished. Have a nice day!

**Comment by RishabhKarnad** [comment]
Closing this issue since it has been answered.
