### ISSUE TITLE
How do I render a checkbox?

### ISSUE THREAD

**Issue by mivd7** [GeekyAnts/vue-native-core#243]
There's nothing in the docs about rendering an input with type checkbox. I've tried several ways but they all come up with this error: 

`Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ReactVueComponent`.

I tried:
`<input type="checkbox" :value="readTerms" :on-press="checkTerms">
<nb-checkbox :checked="readTerms" :onPress="checkReadTerms"></nb-checkbox>   
`
I also tried importing CheckBox directly from react-native. This doesn't throw an error, but none of the functionality seems to work for this component when I put it in. The box itself doesn't get ticked when you click it and the value doesn't change:

` <CheckBox :value="readTerms" :onChange="checkTerms" />`
Please help: how do I get a checkbox to work in a form with Vue Native?

**Comment by mivd7** [comment]
Properly installing native base now makes it possible for me to

**Comment by anark1stx** [comment]
> Installing native base fixed this. now works the way I would expect a checkbox to work.

What do you mean by native base? I'm having the same problem when opening in browser although in mobile works fine, btw I'm not using any external components like you.

**Comment by mivd7** [comment]
Well if you want a CheckBox component, you'll have to use an external package. The default CheckBox component from React Native is deprecated (see https://reactnative.dev/docs/checkbox ) . They advise to use the npm package [react-native-checkbox](https://github.com/react-native-checkbox/react-native-checkbox) instead. [Native base](https://github.com/GeekyAnts/NativeBase) from the same developers as Vue Native also has a CheckBox component, which was the way I solved this.

**Comment by anark1stx** [comment]
I tried it but in web I'm still getting the error, from the other issues I read it seems that vue-native is just not working in web sadly.
