### ISSUE TITLE
$emit() doesn't work

### ISSUE THREAD

**Issue by ormedo** [GeekyAnts/vue-native-core#25]
clean install and replace with this two components.
App.vue ->
````
<template>
  <view class="container">
    <text class="text-color-primary">My First Text</text>
    <children v-on:custom-event="customEventHandler">
          <text class="text-color-primary">My slot</text>
     <template slot="namedslot">
          <text class="text-color-primary">My slot 2</text>
     </template>
    </children>
    </view>
</template>
 <script>
 import children from './children.vue'
 export default {
   components: {
     children
   },
   methods:{
     customEventHandler(value){
       console.log(value);
     }
   }
 }
 </script>
 
<style>
.container {
  background-color: white;
  align-items: center;
  justify-content: center;
  flex: 1;
}
.text-color-primary {
  color: blue;
}
</style>
```

new children.vue ->

```
<template>
    <view>  
        <button class="text-color-primary" :on-press="click(1)" title="HELLOW"></button>
        <slot></slot>
        <button class="text-color-primary" :on-press="click(2)" title="HELLOW2"></button>
        <slot name="namedslot"></slot>
   </view>
</template>

<script>
export default {
    methods: {
        click(value){
            console.log('childer clicked:'+ value);
            this.$emit('custom-event',value);
        }
    }
}
</script>

<style>
.text-color-primary {
  color: green;
}
</style>
```

App vue doesnt receive anything and the view doesnt show as expected

**Comment by smithb1994** [comment]
By the looks of your code, it looks like you forgot to close the `<view>` tag in children.vue
Let me know if that fixes it.

**Comment by sanketsahusoft** [comment]
It's true that <slot> and $emit doesn't work at the moment. We are working towards it.

**Comment by ormedo** [comment]
Closing the view tag doesn`t fix the problem. It was my failure with Copy&Paste code.

I update the code and attach and image of iOS Simulator.

<img width="370" alt="captura de pantalla 2018-06-18 a las 9 08 31" src="https://user-images.githubusercontent.com/23084038/41522652-342b0170-72d7-11e8-8697-7950f8bb5d61.png">

**Comment by neeraj-singh47** [comment]
Right now $emit works only if you have $on in the same component within scripts which listens to the event fired by $emit

**Comment by codeitlikemiley** [comment]
have you tried  adding $on , on the parent component or component which you are listening on the event?
$on should be used on lifehook cycle of mounted...
thats how it work on vue js...
Same principle applies with this one...

**Comment by LiveDuo** [comment]
A quick workaround to invoke functions from childs to parents until $emit is fixed. This allows dumb and smart components to function as expected in Vue Native.

```
/// Child.vue

<template>
  <view>
    **<button title="'button'" :on-press="foo">**
  </view>
</template>

<script>
export default {
	**props: {
		foo: Function
	}**
}
</script>

```


```
/// Parent.vue

<template>
	<view>
		**<child :foo="foo">**
	</view>
</template>

<script>
import Child from './Child.vue'
export default {
	methods: {
		**foo() {
			console.log('i am working')
		}**
	},
	components: { Child }
}
</script>
```

**Comment by neeraj-singh47** [comment]
Please upvote the issue if you guys want it to be fixed. As of now, It doesn't seem to be important since there is a workaround for the $emit.

**Comment by vortechron** [comment]
is $emit never gonna work? its 2019 already :D

**Comment by karolsw3** [comment]
Please, make the $emit work, many users don't know why is it not working and not everyone knows about this workaround...

**Comment by birdlavv** [comment]
I've posted a Bountysource bounty:
https://www.bountysource.com/issues/72753924-bounty-don-t-close-until-fix-is-accepted-emit-doesn-t-work-25

Tracking Repo:
https://github.com/GeekyAnts/vue-native-core/issues/138

**Comment by Sunhat** [comment]
@superMDguy documentation on https://vue-native.io/docs/FAQ.html links to this. Is this no-longer correct?

**Comment by RishabhKarnad** [comment]
@Sunhat An issue has been created in the website repo and docs will be updated to reflect the same. Feel free to create a PR for the website if you are able to.
