### ISSUE TITLE
Question: Lazy Loading Package

### ISSUE THREAD

**Issue by maxencedouet** [GeekyAnts/vue-native-core#253]
Hello, do you have any lazy loading package to recommend ? 

I didn't find any working with vue-native ...

Thks for your help !

**Comment by RishabhKarnad** [comment]
Could you explain the exact use case for lazy loading? We usually don't use it with React Native, since the entire bundle ships with the app.

Images and assets can be lazy loaded though, and cached as well. More info [here](https://reactnative.dev/docs/images#network-images)

**Comment by RishabhKarnad** [comment]
RAM bundles could also help here
https://reactnative.dev/docs/ram-bundles-inline-requires
