### ISSUE TITLE
Question: How to debug when project is showing no errors?

### ISSUE THREAD

**Issue by nashsaint** [GeekyAnts/vue-native-core#256]
Project works perfectly when running locally, either in a simulator or device via qr code but once it's published to expo it crashes. Same thing happened when it's uploaded to TestFlight. The problem is it does not show any messages so I am not sure how to debug.

So, I guess my first question is how will I go about debugging these crashes?

**Comment by RishabhKarnad** [comment]
You could use something like [Sentry](http://sentry.io) for analysing crashes and errors in production.

A quick and dirty fix if you can guess where the crash is happening is to leave `Alert`s instead of `console.log`s in your code so that they show up in production.
