### ISSUE TITLE
Question: render-prop-fn usage?

### ISSUE THREAD

**Issue by Niush** [GeekyAnts/vue-native-core#258]
I am trying to apply `refreshControl` on `scroll-view` using `render-prop-fn`. 
Isn't this the correct way for it?
```vue
<scroll-view :style="{marginTop: 10}">
   <view render-prop-fn="refreshControl" >
     <refresh-control :refreshing="refreshing" :onRefresh="refresh" />
   </view>
   <text>Dummy</text>
</scroll-view>
```

It gives me this error:
<img src="https://user-images.githubusercontent.com/16359077/81825988-ffd38600-9556-11ea-9103-079354988899.png" width="300"/>

Using JSX to render will of course work.
```vue
<scroll-view :style="{marginTop: 10}" :refreshControl="refreshControl()"></scroll-view>
...
...
refreshControl: function(){
  return (
    <RefreshControl refreshing={this.refreshing} onRefresh={this.refresh}/>
  )
}
```

#### Are there other solutions? Shouldn't `render-prop-fn` be working here?

---

**Also**, if I use `flat-list` then I can achieve refresh feature but some render-prop works and some does not.
```vue
<flat-list
  :data="result" :keyExtractor="item => item.id" :refreshing="refreshing" 
  :onRefresh="refresh"
  :onEndReached="info => console.log(info)"
>
    <!-- **Works** -->
    <view render-prop-fn="renderItem">
      <touchable-opacity :style="listItem">
        <text>{{args.item.name}}</text>
      </touchable-opacity>
    </view>
    <!-- **Fails** -->
    <view render-prop="ItemSeparatorComponent">
      <text>-</text>
    </view>
    <!-- **Works** -->
    <view render-prop="ListEmptyComponent">
      <text :style="listItem">Nothing to show</text>
    </view>
   <!-- **Works** -->
    <view render-prop="ListHeaderComponent">
      <text>Lists</text>
    </view>
</flat-list>
```

**Comment by lkho** [comment]
according to your working code, `<scroll-view>`'s `:refreshControl` prop is expecting a `ReactNode`, which should be written in vue template as `render-prop` instead of `render-prop-fn`

**Comment by RishabhKarnad** [comment]
@lkho's comment is correct. As mentioned in the docs: in case the prop type is a function, `render-prop-fn` should be used. If the prop expects a node, `render-prop` should be used.
https://vue-native.io/docs/render-prop.html

In the JSX example for refreshControl, since the function is being called in the template, the prop being provided is not function, but actually a node.

**Comment by Sunhat** [comment]
The documentation is unclear - Where does 'renderItem' even come from

**Comment by Niush** [comment]
@Sunhat `renderItem` comes from React Native itself. https://reactnative.dev/docs/flatlist#required-renderitem
