### ISSUE TITLE
Question: Unable to resolve "...jpg" from "App.vue"

### ISSUE THREAD

**Issue by Tanami** [GeekyAnts/vue-native-core#265]
Hello, while trying to use a local jpg file with Image it appears that vue-native/expo/react-native does not bundle/recognise jpg files as assets despite expo definitely containing assetExts etc in metro-config.

I am using the latest version of vue-native etc.

```
Unable to resolve "assets/needle.jpg" from "App.vue"

undefined Unable to resolve module `assets/needle.jpg` from `App.vue`: assets/needle.jpg could not be found within the project.
```

**Comment by RishabhKarnad** [comment]
@Tanami have you ensured that a relative path is used?

something like `import ... from '../assets/needle.jpg'`

**Comment by Tanami** [comment]
@RishabhKarnad even putting it in the root directory gives the same result.

**Comment by RishabhKarnad** [comment]
could you please provide a code snippet of the usage?

**Comment by Tanami** [comment]
I have resolved this issue by prefixing `./` to the image location i.e. `./needle.jpg` or `./assets/needle.jpg`. Why is this needed? this is not documented anywhere.

**Comment by RishabhKarnad** [comment]
This is standard in ES modules. That's what I was referring to in my first comment.

`./` is the directory of the file, `../` is the parent directory, `../../` is the grandparent and so on.

**Comment by Tanami** [comment]
you should update the Image component example in the documentation as that uses an absolute path

**Comment by RishabhKarnad** [comment]
Sure. Please open an issue on [the website repo](https://github.com/GeekyAnts/vue-native-website/issues), so that this issue is not forgotten.
