### ISSUE TITLE
Question: tips on transforming from existing vue.js project to vue-native?

### ISSUE THREAD

**Issue by gotexis** [GeekyAnts/vue-native-core#269]
Hi guys, I didn't find this in the document. Is it very hard to do?

Is the best thing to do just start a new vue-native app and then copy my vue files to it?

**Comment by gotexis** [comment]
ok i have a bit more understanding now.

vue-native is not vue but basically react-native with vue syntax.

hmm

I guess my next question is how do i keep my CSS libraries (i am using Buefy/Bulma)

But I guess i'm screwed since react-native / vue-native doesnt rely on `div`?

**Comment by RishabhKarnad** [comment]
Hey @gotexis that's correct, Vue Native doesn't support web based UI libraries. React Native has a great ecosystem of UI libraries though (our own [NativeBase](https://nativebase.io) is an example)

Here's a few you can consider:
- NativeBase
- React Native Elements
- React Native Paper

As for transforming a Vue.js project into Vue Native, there is no automated way of doing so. You will probably need to rewrite all of your components, but you might be able to migrate some of the state management and other DOM-independent logic / library usage.
