### ISSUE TITLE
nb-header causes status bar color to change

### ISSUE THREAD

**Issue by JohnVicious** [GeekyAnts/vue-native-core#270]
**Description of the bug**
I set a status bar color in app.json and include a status-bar element at the top of my app. However, whenever I go to a page that has a nb-header, the color of the status bar changes to the default blue, and then every page sets to this color

**To Reproduce**
In App.vue in src, put a status-bar element above app-navigation. Use app.json to set the status bar color.
Create another page and add it to your app drawer and have a nb-header at the top of that page. 
Now navigate to that page and your status bar color will change.

**What I expected**
I expect to be able to set a status bar color in app.json and that color be consistent throughout the application.

**Screenshots**
Code:
app.json:
![image](https://user-images.githubusercontent.com/7691622/85810016-553aaf80-b71f-11ea-9a99-a992ae3f8a7e.png)

App.vue in src:
![image](https://user-images.githubusercontent.com/7691622/85809917-0bea6000-b71f-11ea-9733-33cb06e79539.png)

RecipesScreen with nb-header element:
![image](https://user-images.githubusercontent.com/7691622/85809964-2fada600-b71f-11ea-8f2a-028509f775ba.png)

App:
-Open app
![image](https://user-images.githubusercontent.com/7691622/85809880-ebbaa100-b71e-11ea-8396-fe4fea6b60f9.png)
-Open drawer
![image](https://user-images.githubusercontent.com/7691622/85809835-c2017a00-b71e-11ea-8227-8fd4bbff9993.png)
-Navigate to Recipes which has nb-header and status bar color changes
![image](https://user-images.githubusercontent.com/7691622/85809843-c88ff180-b71e-11ea-81f3-e21ebfdd314c.png)
-Showing that going back to home, the color is changed still
![image](https://user-images.githubusercontent.com/7691622/85809851-cded3c00-b71e-11ea-8e5c-8b7964e330d1.png)

**Did I use `vue-native-cli` to create the project?**
Yes

**Am I using Expo?**
Yes

**Development platform (please complete the following information):**
 - Shell/terminal: [e.g. ZSH, PowerShell]

**Comment by JohnVicious** [comment]
Either this is some type of bug, or I am missing something big here. React shows documentation on creating custom themes and implementing them, however there is zero documentation for vue-native when it comes to styling with themes. I do see that the style-provider is brought over, however again there is no documentation on implementing it with vue-native.

**Comment by JohnVicious** [comment]
To further expand upon this, I downloaded and got the Kitchen Sink NativeBase running. I changed the color in app.json, and also changed the color in all 3 variable files for statusBarColor which is listed as toolbarDefaultBg. When I load the app, the color of the status bar is what I set it at. However, as soon as I click Anatomy or any other page that uses a nb-header element, the status bar color changes and going to any other page does not revert it.

**Comment by doubleh311** [comment]
Seem that you are using native-base UI theme, I have had a work-around on this issue couple days ago.

1. with nb-header you should give it androidStatusBarColor and iosBarStyle with your expected style
2. with screen that does not contain a header give it status-bar component from React with your expected style.

This work is repeatedly because the nb-header sets default status-bar style when the 2 props are not set.

**Comment by JohnVicious** [comment]
> Seem that you are using native-base UI theme, I have had a work-around on this issue couple days ago.
> 
> 1. with nb-header you should give it androidStatusBarColor and iosBarStyle with your expected style
> 2. with screen that does not contain a header give it status-bar component from React with your expected style.
> 
> This work is repeatedly because the nb-header sets default status-bar style when the 2 props are not set.

Are you saying instead of having the status bar at the top of the app-navigation, have it on each screen instead? I will say that is what I originally did, I put a status bar on each screen, including one above the nb-header. That did not work for me. Also, what do you mean "give nb-header androidStatusBarColor"? 

Could you please provide an example of what you mean? That would be extremely helpful and would be much appreciated.

**Comment by doubleh311** [comment]
> Are you saying instead of having the status bar at the top of the app-navigation, have it on each screen instead? 
Yes because the nb-header have set the status-bar and here what I have updated my nb-header

`  <nb-header noShadow :style="style.nbHeader"
        :androidStatusBarColor="'#ffffff'" :iosBarStyle="'dark-content'">
...
</nb-header>`

I use this for screen I have nb-header, with screen I don't use header, give it status-bar with the same style.

**Comment by JohnVicious** [comment]
> > Are you saying instead of having the status bar at the top of the app-navigation, have it on each screen instead?
> 
> Yes because the nb-header have set the status-bar and here what I have updated my nb-header
> 
> ` <nb-header noShadow :style="style.nbHeader" :androidStatusBarColor="'#ffffff'" :iosBarStyle="'dark-content'"> ... </nb-header>`
> 
> I use this for screen I have nb-header, with screen I don't use header, give it status-bar with the same style.

Ah, I understand. Thank you. I will try this in a few hours when I am home and will get back to you. Thank you for your example.

**Comment by doubleh311** [comment]
Hope this could help, I am still looking for some way to make it consistently instead of every screen

**Comment by JohnVicious** [comment]
> 
> 
> Hope this could help, I am still looking for some way to make it consistently instead of every screen.
> 
> Update: I have a solution here
> 
>     1. Use app.json or place an status-bar above app-navigation as your code
> 
>     2. Wrap the nb-header to a new element with the 2 mentioned property and use the new element as header

That is actually not a bad idea, that way any time I want to use the header element, I can use that new element as my header. Just want you to know I just got back to my code and your suggestion of marking the color on the element itself did the trick. Thank you very much.
