### ISSUE TITLE
Using custom components

### ISSUE THREAD

**Issue by fergardi** [GeekyAnts/vue-native-core#28]
Hi everyone! Great project, I'm enjoying it a lot so far.

I was trying to combine this with the https://aframe.io/ framework, but when I add a simple scene under the <view></view> tag, an error occurs.

Is this a closed framework? How can I import custom unsupported components from 3rd party libraries?

Thanks in advance.

**Comment by smithb1994** [comment]
From my understanding, aframe looks like it renders in html.  
React Native and Vue Native don't render HTML, they render native components using HTML like tags.   
If you want to run HTML in Vue Native you need to use another library like [react-native-htmlview](https://github.com/jsdf/react-native-htmlview) or [react-native-render-html](https://github.com/archriss/react-native-render-html).  
I haven't used these libraries before, but they look like they accomplish what you're looking for.

**Comment by fergardi** [comment]
I see. I was excited to use my VueJS knowledge to create a mobile app with AR features. Now i'm a bit disappointed.

Thank you for your response.
