### ISSUE TITLE
Question: This project are developing or close ?

### ISSUE THREAD

**Issue by chatchaisi** [GeekyAnts/vue-native-core#285]
I want to use vuejs native but master was merge 2 month ago ?

**Comment by raynoppe** [comment]
It looks like it is done and dusted. Another great concept to be filed in the archives of coding legends.

**Comment by raynoppe** [comment]
look at ionic view. Not the same end result but half way there.

I just stick to Vue and then wrap it in Cordova. Works a treat.

**Comment by dotNetkow** [comment]
hey @raynoppe, thanks for the [Ionic Vue](https://blog.ionicframework.com/announcing-ionic-vue/) mention, which provides 100+ web-based UI components for web, iOS, and Android. We also recommend [Capacitor](https://capacitorjs.com/solution/vue) to deploy a Vue app to native mobile. It's a modern alternative to Cordova, with improved DX, tooling, and native plugins.

**Comment by RishabhKarnad** [comment]
This project is being maintained but is not in active development.
