### ISSUE TITLE
esllint error when add basic component (text input with inline style) and compiling

### ISSUE THREAD

**Issue by robertoandres24** [GeekyAnts/vue-native-core#29]
if I try to include this basic component that appears in your Docu
https://vue-native.io/docs/basic-components.html
```
<template>
    <text-input
        :style="{height: 40, border-color: 'gray', border-width: 1}"
        v-model="text"
      />
</template>

```
I get the following eslint error when compiling

`[vue/valid-v-bind]
'v-bind' directives require an attribute value.`
![image](https://user-images.githubusercontent.com/11506518/41515981-378c2120-7280-11e8-8460-18bf47e2ab22.png)

and I do not have that global package included
I do not even have an eslintrc 
how can i fix this error?

**Comment by windyflying** [comment]
@robertoandres24 Perhaps, the `border-color` and the `border-width` should be in quotes

**Comment by neeraj-singh47** [comment]
@robertoandres24 You need to use camelCase if you using inline styles.

**Comment by robertoandres24** [comment]
ok thanks. this  also fires an error, and maybe should  change it, the way the data function is written
```data() {
    return {
      text: ""
    };
  }```
regards
