### ISSUE TITLE
Question: 运行报错

### ISSUE THREAD

**Issue by liujianchao1995** [GeekyAnts/vue-native-core#293]
![6fa2a43f5caec03f187fb95ff81cfdd](https://user-images.githubusercontent.com/31613432/104289615-503f2100-54f4-11eb-8276-a1296e3a5a86.jpg)

**Comment by notbryan** [comment]
Please provide more information. Maybe the steps you already followed in the process?

It will help in getting your issue solved quicker instead of just dumping a screenshot.

**Comment by RishabhKarnad** [comment]
Closing due to lack of information. Please follow the issue templates when opening new issues.
