### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by emrecanmuslu** [GeekyAnts/vue-native-core#294]
Hi,
I can run the react native project that I created, but when I want to run the vue native project I just created on android, I get this error;
https://prnt.sc/wm36uu

**Comment by notbryan** [comment]
Note: I am not the project maintainer!

Two tips for your next reported issue in the future:

1. Please don't link to images on external sites when it's about log about; copy pasting of relevant content has been possible for ages for a reason. :)
2. Have you tried running the command with the recommended --verbose flag?

**Comment by RishabhKarnad** [comment]
Closing due to lack of information. Please follow the issue templates when opening new issues.
