### ISSUE TITLE
Question: How to use read sms on vue native

### ISSUE THREAD

**Issue by phontuan** [GeekyAnts/vue-native-core#295]
I want use react-native-read-sms (https://github.com/KetanDhopeshwarkar/react-native-read-sms). Anyone who used it , Please help me. Thanks

**Comment by RishabhKarnad** [comment]
You will need to use Vue lifecycle methods instead of React ones to register and clean up listeners and manage permissions. You may also need to eject your app if it is Expo, or create a bare RN based project since it requires changes to the Android manifest file.
