### ISSUE TITLE
v-on for events

### ISSUE THREAD

**Issue by atilacamurca** [GeekyAnts/vue-native-core#3]
In the example code from <https://vue-native.io/docs/handle-user-input.html> we have:

```html
<view class="container">
  <button v-bind:onPress="handleBtnClickCount" :title="btnTitle" />
  <text class="text-container">{{btnClickCount}}</text>
</view>
```

The `button` use `v-bind:onPress` to handle click, but in Vue we are used to use `v-on:onPress` or `@onPress` instead. Is that any plans to introduce the `v-on` directive?

**Comment by chovy** [comment]
v-bind seems wrong to me.

**Comment by neeraj-singh47** [comment]
v-on is also supported. It's in initial phase though. The syntax for v-on is `v-on:press="handleBtnClickCount()"`.
