### ISSUE TITLE
Question: Can't find variable: __react__vue__options

### ISSUE THREAD

**Issue by kerim92** [GeekyAnts/vue-native-core#304]
Hello

We have 2 pc installed win10x64

installed android studio and configured paths, global variables, working without problem.
installed nodejs latest lts version
installed expo-cli lastest version
installed vue-native-cli lastest version

created project as "vue-native init vue" command

first we have got "Cannot read property content of null" error. 

![image](https://user-images.githubusercontent.com/56412326/110639647-03f52200-81c1-11eb-9361-631b1c8f09b5.png)

after add script tags in App.vue 
error gone and js file builded. 

second error is Can't find variable: __react__vue__options

![image](https://user-images.githubusercontent.com/56412326/110639734-1b340f80-81c1-11eb-8632-f48791a17147.png)

![image](https://user-images.githubusercontent.com/56412326/110639802-2edf7600-81c1-11eb-82d3-252e08adfc24.png)

Edit:

i just try to use react instead of expo. looks like same error:

![image](https://user-images.githubusercontent.com/56412326/110644658-60a70b80-81c6-11eb-98b5-d56032442c2b.png)
 

i am tying to see hello word but since two days can not able to work and no hair left on my head.

any help would be appreciated
thanks in advance

**Comment by RishabhKarnad** [comment]
This is an issue with v0.3.0-rc.1. The bug can be tracked here: #302 

Please install v0.2.0. It should resolve the issue.

**Comment by kerim92** [comment]
Hi,

Thanks for fast response.

i have installed a lot versions of nodejs. currently it is v12.13.0

Installed vue-native-cli, vue-native-scripts selected version 0.2.0 and globally installed.

vue-native init <project name> command installs v0.3.0-rc.1. on project. and problem continues.

i have used "npx vue-native-cli@0.2.0 init vue-latif" command to init a project. but still using v0.3.0-rc.1. version.

at the end, i have installed manually vue-native-scripts 0.2.0 in project folder (not global, just removed  0.3.0 installed 0.2.0) same problem, same message displayed.

i have not able to find which version of node, npm, vue-native, expo-cli, react-native should be installed?

thanks in advance

**Comment by RishabhKarnad** [comment]
Yes, vue-native-cli is currently installing the latest version, which is 0.3.0-rc.1

Please use the following commands to install 0.2.0
```
npm i vue-native-core@0.2.0 vue-native-helper@0.2.0
npm i vue-native-scripts@0.2.0 --save-dev
```

Please restart the app after clearing the Expo app to ensure old dependencies have not been cached. You can use the following command to do that:
```
expo r -c
```

**Comment by kerim92** [comment]
@RishabhKarnad Problem resolved after use your following commands run in project's folder.
npm i vue-native-core@0.2.0 vue-native-helper@0.2.0
npm i vue-native-scripts@0.2.0 --save-dev

Thank you!

**Comment by RishabhKarnad** [comment]
The npm tags have been updated. vue-native-cli should install 0.2.0 by default now
