### ISSUE TITLE
Question:  When will typescript be supported?

### ISSUE THREAD

**Issue by nigel-dewar** [GeekyAnts/vue-native-core#312]
Hi there,

When will typescript be supported? I really wanted to use Vue Native on current project but cannot because no Typescript support, so had to stick with React Native.

I think this feature is really important.

**Comment by nigel-dewar** [comment]
Is there even a way to use Typescript with Vue Native?

**Comment by RishabhKarnad** [comment]
Please use this community plugin for TypeScript support
https://github.com/GeekyAnts/vue-native-core/issues/21#issuecomment-399271609
