### ISSUE TITLE
Question: Example of ejecting Vue-Native app

### ISSUE THREAD

**Issue by jonnycraze** [GeekyAnts/vue-native-core#313]
I have a published app that I need to eject to get some native functionality - IAP and Payments.

When I run the expo eject command, the project is ejected and after relinking a few dependencies it seems to compile fine - however the problem seems to be running in web. When i run: `expo start --web` the project builds and opens in the browser and I am met with the following error: `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

This confuses me, because the App.vue file contains the following:
```
<template>
  <View><Text>testing</Text></View>
</template>

<script>
import {Text, View} from 'react-native';

export default {
  components: { View, Text },
  props: {
    navigation: {
      type: Object
    }
  },
}
</script>
```

Can I not run an ejected app in web at all? I'm trying to run it simply as a test to confirm that things are working before I get any further. Any help or examples of ejected vue-native apps would be GREATLY appreciated. Thank you!

**Comment by RishabhKarnad** [comment]
Web is not supported at the moment. There is an open issue, which can be tracked here: https://github.com/GeekyAnts/vue-native-core/issues/268

Ejected apps should run fine otherwise on iOS and Android. The process is the same as with React Native apps
https://docs.expo.io/bare/customizing/

**Comment by jonnycraze** [comment]
Thank you for the prompt reply - I'll test on android.
