### ISSUE TITLE
"vue-native init" fails due to missing dependency

### ISSUE THREAD

**Issue by cmasdf** [GeekyAnts/vue-native-core#314]
**Description of the bug**
Trying to initialise a new project fails due to missing dependencies.

```✔ Installed Vue Native dependencies

⠋ Installing Vue Native devDependencies
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: <projectName>@0.0.1
npm ERR! Found: react-native@0.63.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.63.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.59.0" from vue-native-scripts@0.2.0
npm ERR! node_modules/vue-native-scripts
npm ERR!   dev vue-native-scripts@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/<username>/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
✔ Installed Vue Native devDependencies
```

**To Reproduce**
1. follow steps according to the [documentation](https://vue-native.io/docs/installation.html) for installation without expo
2. execute the following command according to [Step 1](https://vue-native.io/docs/installation.html#For-React-Native-CLI-users)
    ```
    vue-native init <projectName> --no-expo
    ```

**What I expected**
Succeeding initialisation of a new project

**Screenshots**
not applicable

**Did I use `vue-native-cli` to create the project?**
**Yes**/~~No~~

**Am I using Expo?**
~~Yes~~/**No**

**Development platform (please complete the following information):**
 - OS: macOS 11.2.3
 - Shell/terminal: zsh 5.8 (x86_64-apple-darwin20.0)

**The device on which I run my Vue Native app**
 - Device: not applicable
 - OS: not applicable

**Additional context**
npm 7.10.0
node v14.16.0
vue-native-cli 0.2.0
react-native-cli 2.0.1
****

**Comment by cmasdf** [comment]
closed, due to wrong repository

**Comment by yeheshuah** [comment]
> closed, due to wrong repository

Where is right repository?
Can you share a link to an issue?
