### ISSUE TITLE
Error after a clean installation

### ISSUE THREAD

**Issue by vladoskin7** [GeekyAnts/vue-native-core#317]
**Description of the bug**
Hello! Error after a clean installation using expo.
![123](https://user-images.githubusercontent.com/53142918/116602745-cc8b3200-a934-11eb-9a27-dac7b46c8944.png)

**To Reproduce**

**Did I use `vue-native-cli` to create the project?**
Yes

**Am I using Expo?**
Yes

**Development platform (please complete the following information):**
 - OS: Windows

**Comment by mennobraam** [comment]
Same here!

**Comment by mvtmm** [comment]
Having the same issue after clean installation of vue-native-cli and expo-cli.

**Comment by jamesallan93** [comment]
Are you using npm?
If you are, try yarn.
I wasted 6 hours yesterday trying tons of possible solutions to find out...
Yarn.

Try yarn.

I just made a fresh install, its running \o/
My expo version is 4.5.0

**Comment by joshuaccarroll** [comment]
> Are you using npm?
> If you are, try yarn.
> I wasted 6 hours yesterday trying tons of possible solutions to find out...
> Yarn.
> 
> Try yarn.
> 
> I just made a fresh install, its running \o/
> My expo version is 4.5.0

Thank you for this, @jamesallan93 !!!

For anybody else who comes along behind me, here are the steps I followed to get a working fresh install:

```
npm remove --global vue-native
npm remove --global expo
yarn global add vue-native-cli
yarn global add expo
export PATH="$(yarn global bin):$PATH"
vue-native init testProject
cd testProject
yarn start
```

**Comment by RishabhKarnad** [comment]
Closing since this seems to be resolved. Please create a new issue if this persists with v0.3.0 and the latest CLI
