### ISSUE TITLE
Question: Vue Native for Windows 10?

### ISSUE THREAD

**Issue by Brouilles** [GeekyAnts/vue-native-core#318]
Hi,
Any plan about Windows 10 support like React Native for Windows (https://microsoft.github.io/react-native-windows/)? It can be very usefull!

Thanks.

**Comment by mawlicious** [comment]
This is actually a very good suggestion, however here's my opinion:

1. Though react native is really good, i won't suggest using it for Desktop development, though this library may show it's actually good, i would personally suggest going with Electron, then you can easily use vue as just normal web or using electron-vue
2. If you would still like to do so, then Vue Native is just a wrapper around react native, initialize the vue-native project with the --no-expo flag and then setup React Native windows like you would normally. 

Hope this helps!
