### ISSUE TITLE
Initial setup problem

### ISSUE THREAD

**Issue by pedroMattos** [GeekyAnts/vue-native-core#324]
I did the installation as the documentation teaches using expo, but when running 'npm start' command, the page returned the following error:
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ExpoRootComponent`.

I googled a tutorial to see if I wasn't doing anything wrong, and the steps I took are exactly what the guy in this video did.
https://www.youtube.com/watch?v=Fi79m1Pyf8w&ab_channel=mell0w

**Comment by RishabhKarnad** [comment]
Hi @pedroMattos could you add the details requested in the bug report template? It would make it easier to understand the issue

**Comment by pedroMattos** [comment]
I was only able to use it by taking the example template, configuring it as the documentation asks for it and viewing it from the web it doesn't work at all. I gave up the library

**Comment by RishabhKarnad** [comment]
I guess you were trying to run the app on web. Web is not supported right now https://github.com/GeekyAnts/vue-native-core/issues/268
