### ISSUE TITLE
Question: Is there any way to add supported of <style lang="scss"> in Vue native ?

### ISSUE THREAD

**Issue by boygiandi** [GeekyAnts/vue-native-core#325]
I installed successfully node-sass and now I can import scss file as a JS variable.

```
import styles from 'lunchwme/assets/css/global.scss'
export default {
  data() {
    return {
      styles
    }
  },
  computed: {
    
  }
}
```

Is there anyway to use <style lang="scss"> in .vue file, too ?

**Comment by RishabhKarnad** [comment]
You could try this community plugin
https://github.com/syumai/vue-native-custom-transformer-plugin

**Comment by boygiandi** [comment]
Thank you. I found the way : https://github.com/syumai/vue-native-custom-transformer-plugin/issues/4
