### ISSUE TITLE
Question: Following the installation leads to cannot read property transformFile of undefined

### ISSUE THREAD

**Issue by seejwy** [GeekyAnts/vue-native-core#326]
**Description of the bug**
I have followed the Vue native installation to the t and did npm start. The expo page opens up nicely but when I scanned the code, it tells me "Metro has encountered an error: cannot read property 'transformFile' of undefined".

**To Reproduce**
1. npm install --global vue-native-cli
2. npm install --global expo-cli
3. vue-native init test-project
4. cd test-project
5. npm start
6. Scan the QR code with the EXPO Go app.

**What I expected**
The vue-native app to start up.

**Did I use `vue-native-cli` to create the project?**
Yes

**Am I using Expo?**
Yes

**Development platform (please complete the following information):**
 - OS: Android
 - Shell/terminal: Command Prompt

**The device on which I run my Vue Native app**
 - Device: Samsung Galaxy Note 8 Plus
 - OS: Android 11

**Comment by RishabhKarnad** [comment]
@seejwy please use the bug report template for bugs. Could you edit your description or comment with the info requested in the template?

**Comment by seejwy** [comment]
It works now. So I think someone fixed it. I updated the above anyhow. Thanks and sorry for the late response.
