### ISSUE TITLE
Multi-line css styles inside style="" prevent any styles being applied

### ISSUE THREAD

**Issue by Sunhat** [GeekyAnts/vue-native-core#332]
**Description of the bug**
When writing multi-line css inside a style attribute, no styles are applied

**To Reproduce**
1. Create a vue native component
2. Add multi-line styles
3. See no styles

```
<View style="
    flex-direction: column;
    background-color: red;
">
```

**What I expected**
styles to be applied

**Screenshots**
N/A

**Did I use `vue-native-cli` to create the project?**
No

**Am I using Expo?**
No

**Development platform (please complete the following information):**
 - OS: macOS
 - Shell/terminal: Zsh

**The device on which I run my Vue Native app**
 - Device: iOS
 - OS: 12

**Comment by RishabhKarnad** [comment]
Hi @Sunhat, this syntax is not supported. You can use the CSS-in-JS syntax 

```html
<view :style="{ flexDirection: 'column', backgroundColor: 'red' }"></view>
```

or create a class and pass as a prop.

```html
<template>
    <view class="column"></view>
</template>

<style>
.column {
    flex-direction: column;
    background-color: red;
}
</style>
```
