### ISSUE TITLE
PDF creator  for Vue Native?

### ISSUE THREAD

**Issue by UsamaAltaf** [GeekyAnts/vue-native-core#334]
Hey I need to ask something I created a Application using vue native all the things is fine but now I want to create PDF in my application is there any pdf creator  for Vue Native?

**Comment by SwenVanZanten** [comment]
Vue Native is built upon react native as an abstract wrapper. That means that you can use all of the react native libraries. In this case I give you the first google search result: https://github.com/Hopding/react-native-pdf-lib
