### ISSUE TITLE
How android project use vue-native

### ISSUE THREAD

**Issue by kkmike999** [GeekyAnts/vue-native-core#38]
Readme just said how to run vue-native on my own computer, bug i don't know how to use it in my Android project.

Is there an android project sample?

**Comment by neeraj-singh47** [comment]
@kkmike999 You just need to execute the command `npm start` scan the qr code from your android mobile. You should be able to see the screen in your mobile.

**Comment by neeraj-singh47** [comment]
@kkmike999 For sample app, you can refer to https://github.com/ankitsinghania94/vue-native-todo-app
