### ISSUE TITLE
Pug Templates

### ISSUE THREAD

**Issue by Branksy** [GeekyAnts/vue-native-core#40]
Is it possible to use Pug currently with vue-native, like with regular Vue2.0?

I've installed pug and pug-loader, but no luck getting it to work.

**Comment by gauravprwl14** [comment]
@Branksy From my understanding you cannot use `pug` as its uses HTML Dom to render. But `Vue-Native` does not render HTML Dom, it uses its own native component to render.

**Comment by Branksy** [comment]
I’ve made it work this way:
https://github.com/GeekyAnts/vue-native-core/issues/21
