### ISSUE TITLE
Components not working

### ISSUE THREAD

**Issue by shern91** [GeekyAnts/vue-native-core#41]
I init a vue-native project, try do play around, i keep getting "**Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports**." error.

I created a button components, button.vue

```
<template>
    <view> 
        <button
            :on-press="onPressLearnMore"
            title="Learn More"
            color="#841584"
            accessibility-label="Learn more about this purple button"
        />
    </view>
</template>

<script>
export default {
    methods: {
        onPressLearnMore: function() {
            alert('Hello')
        }
    }
}
</script>
```

and in my App.vue, i import button.vue

```
<template>
  <view class="container">
    <h1>{{ title }}</h1>
      <button>
    </view>
</template>
 
<script>
import button from './button.vue'
export default {
  components: {
     button
  },
  data: function() {
    return {
      message: 'Show Alert',
      title: "Vue Native Core"
    };
  },

  methods: {
    
  }
};
</script>

<style>
.container {
  background-color: white;
  align-items: center;
  justify-content: center;
  flex: 1;
}
.text-color-primary {
  color: blue;
}
</style>
```

but seem like not working and keep getting same error, could somebody help me solve this problem or provide me some useful example? Thank in advance.

**Comment by shern91** [comment]
@gauravprwl14 thanks, just update my code.

**Comment by gauravprwl14** [comment]
@shern91 In Vue-Native, we don't support html Elements. Can Read [React-Native](https://facebook.github.io/react-native/docs/components-and-apis.html) Docs to learn more. 
In Your App.vue file you have used 
```
<h1>{{ title }}</h1>
```
Replace Above code with 
```
<text>{{ title }}</text>
```
