### ISSUE TITLE
v-bind with object not working

### ISSUE THREAD

**Issue by thegeminisociety** [GeekyAnts/vue-native-core#43]
Does v-bind with an object work as of now?

I cannot seem to get this working in Vue Native

Parent
```
<child-component v-bind="anObject"/>
...
data() {
return {
anObject: { d: 'myValue'}
}

}
```

Child
```
<text>{{d}}</text>
...
props:['d']
```

**Comment by neeraj-singh47** [comment]
@thegeminisociety You are not binding it to any variable. You can try binding to a variable `v-bind:test="anObject"` and then in child component declare test as a prop and use `{{test.d}}`

**Comment by thegeminisociety** [comment]
I am trying to achieve this. It works in regular Vue, but not Vue Native.

[https://vuejs.org/v2/guide/components-props.html#Passing-the-Properties-of-an-Object](url)

**Comment by neeraj-singh47** [comment]
@thegeminisociety the nested props is not supported yet.
