### ISSUE TITLE
Object prototype may only be an Object or null.

### ISSUE THREAD

**Issue by TheRealSmolt** [GeekyAnts/vue-native-core#45]
I installed all of the react-native and vue-native stuff today, so it's up-to-date. My issue is that after installing everything the react-native way(with vue-native) I get this error: Object prototype may only be an Object or null. Here's a screenshot. I'm using an android emulator. The console says "BUILD SUCCESSFUL."
![untitled](https://user-images.githubusercontent.com/22825356/42119391-1a83e2ae-7bd9-11e8-85d8-99efcf5c4c38.png)

**Comment by neeraj-singh47** [comment]
@TheRealSmolt Can you share the source code?

**Comment by TheRealSmolt** [comment]
I was moving my code from a vue native project(vue-native init) and this is what I changed from the project, I added a App.vue and put in this code:
**<template>
  <view class="container">
    <text v-if="clickCount < 30" class="text-color-primary text-large">Times Clicked:</text>
    <text v-if="clickCount >= 30 && clickCount < 70" class="text-color-primary text-large">You're really spending time on this?</text>
    <text v-if="clickCount >= 70 && clickCount < 100" class="text-color-primary text-large">This is sad.</text>
    <text v-if="clickCount >= 100 && clickCount < 150" class="text-color-primary text-large">Do you even have a life?</text>
    <text v-if="clickCount >= 150" class="text-color-primary text-large">What are you doing?</text>

    <text class="text-color-primary">{{clickCount}}</text>

    <view class="button">
      <button
      :on-press="click"
      title="Click"
      color="#841584"
      />
    </view>
  </view>
</template>

<script>
export default
{
  data: function()
  {
    return
    {
      clickCount: 0
    }
  },
  methods:
  {
    click: function()
    {
      this.clickCount++;
    }
  }
}
</script>

<style>
.container
{
  background-color: white;
  align-items: center;
  justify-content: center;
  flex: 1;
}

.button
{
  width: 300;
  margin-top: 40;
}

.text-color-primary
{
  color: #841584;
  margin-top: 30;
  margin-left: 15%;
  margin-right: 15%;
  font-size: 40;
  font-weight: bold;
  text-align: center;
}

.text-large
{
  height: 300;
}
</style>**
Which did work in the original project.

**Comment by TheRealSmolt** [comment]
For whatever reason, after recreating the project, it worked without any errors. For anyone with the same issue, I just followed step by step whats on the installation page.
