### ISSUE TITLE
Live reload not working (Windows 10 w/Ubuntu)

### ISSUE THREAD

**Issue by KevinBatdorf** [GeekyAnts/vue-native-core#47]
When using the Linux subsystem on Windows 10 making changes to the files has no effect. Even if I restart the `start` script or press `R` nothing changes from the original app. No matter what I try I can only see "My Vue Native App"

Maybe it has something to do with symlinks? Not sure. Thanks!

**Comment by neeraj-singh47** [comment]
@KevinBatdorf Are you using a VM or WSL?

**Comment by KevinBatdorf** [comment]
@neeraj-singh47 WSL

**Comment by neeraj-singh47** [comment]
@KevinBatdorf Can you try removing .git/index.lock

**Comment by KevinBatdorf** [comment]
Hi @neeraj-singh47 Sorry for the late reply. It works on my Macbook so I've been playing around with it there while traveling. Back at home now. I used `vue-native init test-app` so it wont have a .git directory, right? 

I'll fine developing on my Mac but I can help debug here if you have any other suggestions you'd like me to try out.

**Comment by neeraj-singh47** [comment]
Closing the issue due to inactivity
