### ISSUE TITLE
Cannot find module 'metro/src/transformer'

### ISSUE THREAD

**Issue by RafaelAugustoS** [GeekyAnts/vue-native-core#48]
when trying to run the app it returns me the error `Cannot find module 'metro/src/transformer'` in terminal

**Comment by sumesh1993** [comment]
getting the same error, after initiating an app without crna.
when i input npm start for the first time, i am getting this error

**Comment by RafaelAugustoS** [comment]
@neeraj-singh47 exactly as the friend said, as soon as he created the app without crna and I'll start, he gives this error

**Comment by gauravprwl14** [comment]
@RafaelAugustoS In Latest version of `react-native(0.56.0)` they have change the metro bundler dependency. can you try downgrading the `react-native(0.55.2)` package and reinstall the node_modules.

**Comment by neeraj-singh47** [comment]
@RafaelAugustoS We'll update the dependency based on the latest react-native soon.

**Comment by RafaelAugustoS** [comment]
@gauravprwl14 works, but now it generates the following error

` bundling failed: Error: Plugin 0 specified in "/Users/rafaelaugusto/Documents/Aplicativos/VueNative/teste/node_modules/babel-preset-react-native/index.js" provided an invalid property of "default" (While processing preset: "/Users/rafaelaugusto/Documents/Aplicativos/VueNative/teste/node_modules/babel-preset-react-native/index.js")
    at Plugin.init (/Users/rafaelaugusto/Documents/Aplicativos/VueNative/teste/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/Users/rafaelaugusto/Documents/Aplicativos/VueNative/teste/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
    at /Users/rafaelaugusto/Documents/Aplicativos/VueNative/teste/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/rafaelaugusto/Documents/Aplicativos/VueNative/teste/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/rafaelaugusto/Documents/Aplicativos/VueNative/teste/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at /Users/rafaelaugusto/Documents/Aplicativos/VueNative/teste/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /Users/rafaelaugusto/Documents/Aplicativos/VueNative/teste/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (<anonymous>)
`

**Comment by gauravprwl14** [comment]
@RafaelAugustoS It is because of the latest `babel-preset-react-native(5.0.0)` package, you have to downgrade `babel-preset-react-native` to `4.0.0` and try reinstalling the node_modules.

**Comment by RafaelAugustoS** [comment]
@gauravprwl14 It worked, Thanks

**Comment by ShailenNaidoo** [comment]
I tried all the methods that everyone is suggesting but nothing... still error

**Comment by alexstomp** [comment]
I couldn't get the environment to work at all for a whole day because of this error. Kept removing node_modules/yarn.lock, and trying to re-build with different versions to no avail. 

This ended up being the solution for me: https://stackoverflow.com/questions/39778607/error-running-react-native-app-from-terminal-ios

Xcode was not mapping to the command line tools. If you're having this issue.. before you start trying older versions of packages and ~banging your head~ running in circles.. just make sure your Xcode Location is selected for command line tools.

**Comment by neeraj-singh47** [comment]
Vue Native CLI now installs v0.55.4 by default and v0.56 is not supported by vue-native as of now. We hope to add support for the latest react-native version as soon as possible

**Comment by chinavane** [comment]
vueTransformerPlugin.js

`var semver = require('semver');
var vueNaiveScripts = require("vue-native-scripts");
var reactNativeVersionString = require("react-native/package.json").version;
var reactNativeMinorVersion = semver(reactNativeVersionString).minor;

if (reactNativeMinorVersion >= 56) {
  upstreamTransformer = require("metro/src/reactNativeTransformer");
} else if (reactNativeMinorVersion >= 52) {
  upstreamTransformer = require("metro/src/transformer");
} else if (reactNativeMinorVersion >= 47) {
  upstreamTransformer = require("metro-bundler/src/transformer");
} else if (reactNativeMinorVersion === 46) {
  upstreamTransformer = require("metro-bundler/build/transformer");
} else {
  // handle RN <= 0.45
  var oldUpstreamTransformer = require("react-native/packager/transformer");
  upstreamTransformer = {
    transform({ src, filename, options }) {
      return oldUpstreamTransformer.transform(src, filename, options);
    }
  };
}
var vueExtensions = ["vue"]; // <-- Add other extensions if needed.

module.exports.transform = function({ src, filename, options }) {
  if (vueExtensions.some(ext => filename.endsWith("." + ext))) {
    return vueNaiveScripts.transform({ src, filename, options });
  }
  return upstreamTransformer.transform({ src, filename, options });
};
`

**Comment by Madhur2207** [comment]
Just do "react-native upgrade"

**Comment by Hol7** [comment]
this is what i'm facing , i do need some Help


(node:9023) UnhandledPromiseRejectionWarning: Error: Cannot find module 'vue-native-scripts'
Require stack:
- /home/talent/demo/vueTransformerPlugin.js
- /home/talent/demo/node_modules/metro/src/JSTransformer/worker.js
- /home/talent/demo/node_modules/metro/src/DeltaBundler/Transformer/getTransformCacheKey.js
- /home/talent/demo/node_modules/metro/src/DeltaBundler/Transformer.js
- /home/talent/demo/node_modules/metro/src/Bundler.js
- /home/talent/demo/node_modules/metro/src/IncrementalBundler.js
- /home/talent/demo/node_modules/metro/src/index.js
- /home/talent/demo/node_modules/@react-native-community/cli/build/tools/loadMetroConfig.js
- /home/talent/demo/node_modules/@react-native-community/cli/build/commands/server/runServer.js
- /home/talent/demo/node_modules/@react-native-community/cli/build/commands/server/server.js
- /home/talent/demo/node_modules/@react-native-community/cli/build/commands/index.js
- /home/talent/demo/node_modules/@react-native-community/cli/build/cliEntry.js
- /home/talent/demo/node_modules/@react-native-community/cli/build/index.js
- /home/talent/demo/node_modules/react-native/local-cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/talent/demo/vueTransformerPlugin.js:2:24)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
(node:9023) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9023) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
