### ISSUE TITLE
Cannot get the reference to the camera component.

### ISSUE THREAD

**Issue by NikoPeltoniemi** [GeekyAnts/vue-native-core#49]
Here's my code:
`<camera class="container" :type="type" :ref="ref => {camera = ref}"/>`
But this.camera returns null. Could you write an example of the camera that actually takes a picture?

**Comment by gauravprwl14** [comment]
@NikoPeltoniemi  you can declare a reference like

```
<camera class="container" :type="type" :ref="camera" />
```
and you can access camera reference like

```
this.$refs.camera
```

**Comment by Peretz30** [comment]
How can I use callback in ref in Vue Native ? https://github.com/vuejs/vue/issues/4998
Can't make [ref-vue plugin](https://github.com/vueComponent/vue-ref) work for me.
