### ISSUE TITLE
Component inside attribute

### ISSUE THREAD

**Issue by hrsabbir** [GeekyAnts/vue-native-core#50]
`<Button
  icon={
    <Icon
      name='arrow-right'
      size={15}
      color='white'
    />
  }
  title='BUTTON WITH ICON COMPONENT'
/>`

How can I do this in vue-native?

**Comment by neeraj-singh47** [comment]
@hrsabbir Assuming you are using react-native-elements >= v1.0.0-beta5. You can follow the below steps to implement the icon.
1) `<button :icon="icon" title='BUTTON WITH ICON COMPONENT' />`.
2) Within the scripts `import React from 'react'` and declare icon as data.
`data: {
              icon: <Icon
                           name='arrow-right'
                           size={15}
                           color='white'
                        />
             }`
