### ISSUE TITLE
Gesture support

### ISSUE THREAD

**Issue by orels1** [GeekyAnts/vue-native-core#51]
Hey there!
First of all, thanks for this project. I'm currently developing an app for a website using it and it was nice experience so far (not prod, just a sideproject).

I have a question about gestures and event binding in general. But first things first.
I have a view that looks like this

```vue
<template>
  <view
    :onStartShouldSetResponder="shouldRespond"
    :onMoveShouldSetResponder="shouldRespond"
    :onResponderGrant="respond"
    :onResponderReject="reject"
  >
  </view>
</template>
```

```js
export default {
  methods: {
    shouldRespond: () => true,
    respond: function(evt) {
      console.log('responding!', evt);
    },
    reject: function(evt) {
      console.log('rejected!', evt);
    } 
  }
}
```

And nothing seems to trigger when doing any kind of gestures on that view.

Also, another thing is that i'm a bit confused with how the even binders behave. In the docs they say to use classic `v-bind`, and it works. While in react-vue docs - they say to use the familiar @click and @press and so on. And they work as well, but only if you call them in the handler, like `@press="expand(index)` or smth like that.

If anyone could help me out with that confusion - that would be awesome!

**Comment by Samaritan1011001** [comment]
```html
<template>
  <view class= "container"
    :onStartShouldSetResponder="()=>{return true}"
    :onResponderGrant="() => console.log('granted')"
    :onResponderMove="handleResponderMove"
    :onResponderRelease="() => console.log('released')"
  >
    <text>Button</text>
  </view>
</template>
```
```script
<script>
export default {
    methods: {
      handleResponderMove: function(evt){
        console.log('touch move at:', 'X='+evt.nativeEvent.locationX, 'Y='+evt.nativeEvent.locationY);
      },
  }
}
 </script>
```
The above code should work just fine.

**Comment by Samaritan1011001** [comment]
And to try and clear the confusion, v-bind/v-on can be used in it's full form or it can be used in it's short hand form which are `:` and `@` for `v-on`. These are just syntatic sugars that help you write  cleaner code. Referenced from here : https://vuejs.org/v2/guide/syntax.html#v-bind-Shorthand 
If used in the above code, it looks like this : 
```html
<template>
  <view class= "container"
    :on-start-should-set-responder="()=>{return true}"
    @responder-grant="grant()"
    :on-responder-move="handleResponderMove"
    :on-responder-release="() => console.log('released')"
  >
  </view>
</template>
```
Infact, `v-on` is not supported in `react-native` but the support for it is added in Vue-Native. So, that's how it can be used if needed.

**Comment by orels1** [comment]
This is what I was confused with - the translation layer between vue-native and react-native.
Thanks for clearing that for me!
