### ISSUE TITLE
text-input content shake

### ISSUE THREAD

**Issue by Aysnine** [GeekyAnts/vue-native-core#52]
## package.json

```js
{
  "devDependencies": {
    "jest-expo": "~27.0.0",
    "react-native-scripts": "1.14.0",
    "react-test-renderer": "16.3.1",
    "vue-native-scripts": "0.0.10"
  },
  "dependencies": {
    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "vue-native-core": "0.0.5",
    "vue-native-helper": "0.0.8"
  }
}
```

## Display

![1531614561510_video 1](https://user-images.githubusercontent.com/10137653/42729461-eee6451c-880b-11e8-91a0-6ac02d224448.gif)

## Code

https://vue-native.io/docs/handle-user-input.html

**Comment by Samaritan1011001** [comment]
This is because of the older version of `vue-native-core` that you are using. 
Run:
``` npm install vue-native-core@0.0.7 --save```
