### ISSUE TITLE
How to pass class as style props in component

### ISSUE THREAD

**Issue by dacsang97** [GeekyAnts/vue-native-core#56]
I use <style> and `class` to define style for element. In component, I see in the RN Debugger, `class` had been compiled to style props as the number of style.

![img](https://i.imgur.com/79oZjJs.png)

But I can't use this number in `<template>` tag to override internal style.

Here is my pseudo code:
*Parent*
```html
<template>
  <test-view class="test" />
</template>
<style>
.test {
  border-radius: 75
}
</style>
```

*Test View component*
``` html
<template>
  <view :style="[style, { width: 30, height: 30}]"></view>
</template>

<script>
export default {
  props: {
    class: String,
    style: Object | Array,
  },
  created() {
    console.log(this);
  }
}
</script>
```

Test View only has `{ width: 30, height: 30}` in style.

**Comment by neeraj-singh47** [comment]
@dacsang97 So you want to reuse the class within your test-view component?

**Comment by dacsang97** [comment]
@neeraj-singh47 yes, I want to reuse some class.

**Comment by gauravprwl14** [comment]
@dacsang97 I think it is working.
My Parent Component
```
<template>
  <test-view class="test" />
</template>
<script>
import testView from "./testVue";
export default {
  components: {
    testView
  }
};
</script>
<style>
.test {
  border-radius: 75;
  background-color: blue;
  flex: 1;
  justify-content: center;
  align-items: center;
}
</style>
```

And My Child Component
```
<template>
  <view :style="[style]"><text>Parent Style is Applied</text></view>
</template>

<script>
export default {
  props: {
    class: String,
    style: Object | Array
  },
  created() {
    console.log(this);
  }
};
</script>
```


And Here is A Screen Shot
![image 12](https://user-images.githubusercontent.com/20392678/43260887-65da27d4-90f8-11e8-9366-a590fe9076e4.png).
