### ISSUE TITLE
Cannot load external css or scss file

### ISSUE THREAD

**Issue by pdlima** [GeekyAnts/vue-native-core#58]
I'm trying to load external css like this and it says 'Unable to resolve'

`import './style.css'`

What is the current recommended way to import css or scss files?

**Comment by neeraj-singh47** [comment]
@pdlima Right now you cannot import a css file. To load external styles you can do something like this.
1) Create a new js file and you can have something like this for an example 
`export default styles = {
  container: {
    backgroundColor: 'black',
    alignItems: 'center',
    justifyContent: 'space-around',
    flex: 1,
    flexDirection: 'column'
  }
}`
2) You can then import the style into vue file and declare it within computed section and then use it within your template
`import style from './mainStyle.js';`
`computed: {
    style: function (){
      return style
    }
  }`
`<view :style="style.container">`
