### ISSUE TITLE
Cannot find module 'vue-native-scripts'

### ISSUE THREAD

**Issue by Tzikas** [GeekyAnts/vue-native-core#59]
I'm just following the getting started instructions:

npm install -g vue-native-cli
vue-native init project // Initializes crna project
cd project
npm install 
npm start

and I get the following: 

```$ npm start

> cmon@0.1.0 start /Users/Squirrel/Documents/Code/VUE/cmon
> react-native-scripts start

10:57:02 AM: Starting packager...
***ERROR STARTING PACKAGER***
Starting React Native packager...
Scanning folders for symlinks in /Users/Squirrel/Documents/Code/VUE/cmon/node_modules (14ms)

Cannot find module 'vue-native-scripts```

**Comment by Samaritan1011001** [comment]
It seems to not have `vue-native-scripts` installed. I tried this and was not able to reproduce the issue. 
You can give the following a try : 
• After you have created the project, run `npm install vue-native-scripts --save-dev` and then `npm start`.
• Clear the cache with `npm start -- --reset-cache`

**Comment by Tzikas** [comment]
It worked once I updated my yarn which was out of date.  Thank you.

**Comment by LiveDuo** [comment]
It happens when you force stop the vue-native init command early.
