### ISSUE TITLE
what's the difference between weex and vue-native?

### ISSUE THREAD

**Issue by WestDoorBlowAsh** [GeekyAnts/vue-native-core#6]

**Comment by HughesWang** [comment]
http://vue-native.io/docs/index.html#What-is-Vue-Native

**Comment by Lxxyx** [comment]
## Vue Native
Vue Native is a mobile framework to build truly native mobile app using Vue.js. Its is designed to connect React Native and Vue.js.

Vue Native is a wrapper around React Native APIs, which allows you to use Vue.js and compose rich mobile User Interface.

## Weex
Weex is a framework for building high-performance mobile applications with modern web development experience.

Weex can use Rax and Vue.js as JS Framework,and has Vue.js offical support.
