### ISSUE TITLE
Passing non string properties to attributes

### ISSUE THREAD

**Issue by LiveDuo** [GeekyAnts/vue-native-core#60]
Hi, I'm having trouble passing integers and booleans to template html tags as shown below.

Don't work
`<Ionicons name="md-checkmark-circle" size="32" color="green" />`
`<Ionicons name="md-checkmark-circle" size="{32}" color="green" />`
`<scroll-view showsVerticalScrollIndicator="false"> ... </scroll-view>`
`<scroll-view showsVerticalScrollIndicator="{false}"> ... </scroll-view>`

Work
`<Ionicons name="md-checkmark-circle" color="green" />`
`<scroll-view> ... </scroll-view>`

**Comment by leopiccionia** [comment]
Have you tried using  `v-bind:size="32"` and `v-bind:showsVerticalScrollIndicator="false"`, or shorthands `:size="32"` and `:showsVerticalScrollIndicator="false"` (please notice `:` prefix)?

**Comment by Samaritan1011001** [comment]
@LiveDuo If you want to pass a value to any prop, use the `:` prefix just like how @leopiccionia  has mentioned.

**Comment by LiveDuo** [comment]
Thanks @leopiccionia and @Samaritan1011001 . 

I'm trying to figure out which is the right syntax to use. There is another issue. I'm confused whether I should use brackets before the attribute variable or not. In some cases they seem needed and in other cases they are not!

work
:snapToAlignment={"center"} //eslint throws a bunch of errors
:showsVerticalScrollIndicator="true"

dont work
:snapToAlignment="center"
:showsVerticalScrollIndicator={"true"}



eslint errors:
![image](https://user-images.githubusercontent.com/370612/43798881-92cea85a-9a94-11e8-949c-6cf8aeb933ea.png)

**Comment by leopiccionia** [comment]
@LiveDuo You don't need to use `:` with string constants (`"center"`, `"dark-content"`) as this is the default HTML behavior.

Both `snapToAlignment="center"` or `:snapToAlignment="'center'"` (single quote inside double quote, or vice-versa) behave the same.

It seems from your examples that `:attr={"value"}` behaves somehow like `:attr='"value"'`. I don't know if this is expected HTML behavior, or some Vue particularity/bug. Anyway, you aren't expect to use `{` and `}` as outermost characters except inside JSX -- and I suspect that's the meaning of `unexpect-character-in-unquoted-attribute-value` ESLint rule.

With `v-bind:` or `:`, the content of outermost quotes (on, in this bizarre case, brackets) will be interpreted as a JavaScript expression:
* `{"center"}`: expression `"center"`, evals to string
* `"true"`: expression `true`, evals to boolean
* `{"dark-content"}`: expression `"dark-content"`, evals to string
* `"center"`: expression `center`, evals to the value of `this.center`
* `{"true"}` expression `"true"`, evals to string
* `"dark-content"`: expression `dark-content`, evals to `this.dark - this.content`

This is default Vue template semantics, so be assured to know it.

**Comment by LiveDuo** [comment]
That cleared up some many things. Thanks
