### ISSUE TITLE
npm run eject react native  can not build ios app successfully

### ISSUE THREAD

**Issue by lenvonsam** [GeekyAnts/vue-native-core#61]
I choosed vue-native init <projectName> this mode to create my project, after npm run eject choosing react native only mode, the ios project can not pod install, because the `ExpoKit` from `http://github.com/expo/expo.git`, tag `ios/2.5.10` always RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
how to solve this problem
![image](https://user-images.githubusercontent.com/10168476/43873039-87a87374-9bb7-11e8-884b-c2722531d766.png)

**Comment by neeraj-singh47** [comment]
@lenvonsam Seems like a networking issue. Can you try again and provide the update about the issue?
