### ISSUE TITLE
Navigation props inconsistencies

### ISSUE THREAD

**Issue by LiveDuo** [GeekyAnts/vue-native-core#63]
Navigation props inconsistencies

I was trying to understand vue-native/react-native navigation and come up with a strange at first glance behavior. It seems that the required prop for navigation is different when navigation used in <template> and when is used in <script>. The <template> requires navigation to be imported as Object while  <script> requires navigation to be imported as { type: Object }. Is that intentional and if so what is the reasoning behind this.

```
<template>
    <button :on-press="() => navigation.navigate('TabNavigation')" title="button" />
</template>

<script>
export default {
	props: {
		navigation: Object
	}
}
</script>
```

```
<script>
export default {
	props: {
		navigation: { type: Object }
	},
	methods: {
	    login() {
			this.navigation.navigate('TabNavigation')
		}
	}
}
</script>
```

**Comment by LiveDuo** [comment]
I expected that as well. I have that this.navigation.navigate('TabNavigation') in <script > works only with navigation: { type: Object } and :on-press="() => navigation.navigate('TabNavigation')" works only with and navigation: Object.

Do they work as expected for you?

**Comment by Samaritan1011001** [comment]
@LiveDuo, I tried this and both seems to work as expected. @leopiccionia is right about it.
