### ISSUE TITLE
render prop fn not work

### ISSUE THREAD

**Issue by lenvonsam** [GeekyAnts/vue-native-core#67]
when i use flat-list component, and use <view render-prop-fn="renderItem"/>, then i occurs error of typeError: renderItem is not a function
how to slove it ?
screencrop
![image](https://user-images.githubusercontent.com/10168476/45015893-a44cb780-b055-11e8-9b65-54385394319e.png)
![image](https://user-images.githubusercontent.com/10168476/45015899-ab73c580-b055-11e8-894b-b6fd91471222.png)

**Comment by neeraj-singh47** [comment]
@lenvonsam Have to updated vue-native-scripts, vue-native-compiler and vue-native-helper to latest versions?

**Comment by lenvonsam** [comment]
"vue-native-scripts": "0.0.12"
"vue-native-helper": "0.0.9"
not use vue-native-compiler
