### ISSUE TITLE
why flatlist not support slot tag

### ISSUE THREAD

**Issue by lenvonsam** [GeekyAnts/vue-native-core#68]
when i put <slot> tag into flatlist, it always occurs renderItem is not function
![image](https://user-images.githubusercontent.com/10168476/45068709-5f7b5c00-b0fb-11e8-857a-5e140ec78b7a.png)
![image](https://user-images.githubusercontent.com/10168476/45068711-6609d380-b0fb-11e8-90c2-6d5181a7e940.png)

**Comment by neeraj-singh47** [comment]
@lenvonsam Slot is something which is not according to the use case of the flat list. It's how you want to render your item in the list.

**Comment by lenvonsam** [comment]
i want flat list use slot to make a common component for my project, how to make it work?
@neeraj-singh47

**Comment by neeraj-singh47** [comment]
@lenvonsam You'll have to create a common component including the flat list as well. It doesn't make sense to create a common component just for renderItem when the data is same.

**Comment by lenvonsam** [comment]
I want to make component list react-native-pull, which can use everywhere just defining fewer custom params,
not like everywhere using flatlist must define many same params that's too redundancy
@neeraj-singh47

**Comment by neeraj-singh47** [comment]
@lenvonsam This cannot be achieved through vue right now since renderItem is a required functionality and the render-prop-fn is mapped to the prop and if we use slot. It's not directly accessible as a prop to the flat list. Did you try out the react-native-pull? It should work since the implementation is on react.

**Comment by neeraj-singh47** [comment]
@lenvonsam Were you able to implement the feature?
