### ISSUE TITLE
[Comparison] What's the pros/cons and differences between vue-native and vue-nativescript?

### ISSUE THREAD

**Issue by jefflam** [GeekyAnts/vue-native-core#7]
First off, super excited to see work on this being done! Vue is an awesome framework but was direly missing the mobile love. 

Am currently building a mobile app and would love to know the differences between vue-native and vue-nativescript. Thanks!

**Comment by Lxxyx** [comment]
Vue Native is based on React Native. But NativeScript is a different platform.
In my option, React Native is an better platform for developing native applications.

**Comment by jefflam** [comment]
Thanks for responding @Lxxyx. When you say based on react native -- and I've also seen the slides -- does this mean that this this is compiled to react-native code which is then compiled to the mobile apps?

**Comment by Lxxyx** [comment]
@jefflam Yes, First transform to React Native code. Then use react native sdk for running at device.

**Comment by niutech** [comment]
For React Native vs NativeScript comparison, I recommend reading these articles:
https://teabreak.e-spres-oh.com/nativescript-vs-react-native-7c7f230b3e
https://www.quora.com/What-are-the-key-difference-between-ReactNative-and-NativeScript
