### ISSUE TITLE
 About property binding, the binding type is a function type problem

### ISSUE THREAD

**Issue by chinavane** [GeekyAnts/vue-native-core#70]
The parent component passes data to the child component, passing data types such as strings, numbers, etc., but cannot pass function types. If you want to pass a function to a subcomponent and call the method to call back the function of the parent component through the subcomponent, you need to perform event listener and emit operation through eventemitter3. In the end, I want to confirm, is it possible to pass methods to subcomponents?

**Comment by neeraj-singh47** [comment]
@chinavane Yes it is possible. You can take a look into this. https://github.com/GeekyAnts/vue-native-core/issues/25#issuecomment-412457861
