### ISSUE TITLE
Does it support the definition and use of custom directive?

### ISSUE THREAD

**Issue by chinavane** [GeekyAnts/vue-native-core#73]
After a certain attempt, it is confirmed that global component definition, local component definition, global filter definition, and local custom filtering can be performed, but it is not successful when testing the custom directive. Does it support the definition and use of custom directive?

**Comment by neeraj-singh47** [comment]
Directives are not supported only components are supported

**Comment by chinavane** [comment]
```
 Vue.filter('toLow',(v)=>{
    return v.toLowerCase();
  })
```
filter can also be defined and used
