### ISSUE TITLE
Setup with React Native,class does not work

### ISSUE THREAD

**Issue by chinavane** [GeekyAnts/vue-native-core#74]
```
1.react-native init vueNativeTry

2.cd vueNativeTry

3.
npm install vue-native-core vue-native-helper --save
npm install vue-native-scripts --save-dev

4.vueTransformerPlugin.js
var upstreamTransformer = require("metro/src/reactNativeTransformer");
var vueNativeScripts = require("vue-native-scripts");
var vueExtensions = ["vue"];
module.exports.transform = function({ src, filename, options }) {
  if (vueExtensions.some(ext => filename.endsWith("." + ext))) {
    return vueNativeScripts.transform({ src, filename, options });
  }
  return upstreamTransformer.transform({ src, filename, options });
};

5.rn-cli.config.js
module.exports = {
  getTransformModulePath() {
    return require.resolve("./vueTransformerPlugin.js");
  },
  getSourceExts() {
    return ["vue"];
  }
};

6.rename App.js to App.vue
<template>
  <view class="container">
    <text class="text-color-primary">My Vue Native App</text>
    </view>
</template>
<style>
.container {
  background-color: white;
  align-items: center;
  justify-content: center;
  flex: 1;
}
.text-color-primary {
  color: blue;
}
</style>

```
![snip20180907_14](https://user-images.githubusercontent.com/8588836/45196139-676b0580-b28d-11e8-8dd9-9ab500d0c06a.png)
class did not work.please help! thx.

if i edit style,it can work very well!

**Comment by neeraj-singh47** [comment]
@chinavane Seems like you are using react-native > 55. Can you update vue-native-cli and create a new project.

**Comment by chinavane** [comment]
I use this way to create project,it's ok.
vue-native init <projectName> --no-crna

**Comment by chinavane** [comment]
yes,it's working now!thx.

**Comment by donvie** [comment]
still getting the error solution please

**Comment by lost-vetern** [comment]
i am using 
vue-native inti projectname --no-crna 
and when ever i run my vue native app it starts the app.js file instead of app.vue ... 
any solution ??

**Comment by neeraj-singh47** [comment]
@lost-vetern Can you verify that you are using RN < 0.55.4 and the config is similar to https://github.com/GeekyAnts/vue-native-starter-app

**Comment by lost-vetern** [comment]
react-native-cli: 2.0.1
react-native: 0.57.1
and the "rn-cli.config.js" files are similar

**Comment by neeraj-singh47** [comment]
@lost-vetern You are using react-native > 0.55.4. It's not supported yet
