### ISSUE TITLE
vuex persist's question

### ISSUE THREAD

**Issue by chinavane** [GeekyAnts/vue-native-core#75]
How can I persist data when using vuex? Vuex-persist was used before, but it is not working properly now.

**Comment by neeraj-singh47** [comment]
@chinavane Here's an example of vuex persistance. https://github.com/GeekyAnts/vue-native-starter-app/tree/feat/dataPersistence

**Comment by chinavane** [comment]
ok,i'll check it.thank you very much.

**Comment by neeraj-singh47** [comment]
@chinavane You can close the issue if it's working
