### ISSUE TITLE
how to use new Vue to render customer plugin

### ISSUE THREAD

**Issue by lenvonsam** [GeekyAnts/vue-native-core#77]
I want to define customer plugin with Vuejs
like this
![image](https://user-images.githubusercontent.com/10168476/45284589-85499c00-b513-11e8-9ce3-1d5216b09552.png)
but i can not find node in react native, how to make it?

**Comment by neeraj-singh47** [comment]
@lenvonsam You cannot create a functional render. Vue native does not work on html tags
