### ISSUE TITLE
Vue Native Router can not listen back to origin page

### ISSUE THREAD

**Issue by lenvonsam** [GeekyAnts/vue-native-core#78]
i use StackNavigator, when app lauched, page a when call beforeMount method, when page a navigate to page b , and from page b goback to page a , the page a 's beforeMount not invoke, how to make this work.

**Comment by neeraj-singh47** [comment]
@lenvonsam Can you try beforeUpdate method?

**Comment by lenvonsam** [comment]
It always just invoke once time when i use beforeUpdate method.
@neeraj-singh47

**Comment by neeraj-singh47** [comment]
@lenvonsam So it's invoked every time you navigate from one page to another?

**Comment by lenvonsam** [comment]
i find the way , but not the beforeUpdate

**Comment by jonnycraze** [comment]
What was the solution for doing this?
