### ISSUE TITLE
vue-native init error

### ISSUE THREAD

**Issue by ThoughtZer** [GeekyAnts/vue-native-core#8]
I'm trying to init a project, but met a problem
![image](https://user-images.githubusercontent.com/23690568/41327757-3dad4994-6ef7-11e8-865d-006e8a127b52.png)
What do I need to do?

**Comment by ThoughtZer** [comment]
@chshouyu Do you know what the problem is?
There is a problem description, but there is no solution.
https://foundation.zurb.com/forum/posts/36676-foundation-new-error-enoent-no-such-file-or-directory-uv_chdir

**Comment by chovy** [comment]
https://github.com/isaacs/node-graceful-fs/issues/115

**Comment by ThoughtZer** [comment]
@chovy Sorry, I didn't get what you meant. How do I change it? Can you give me a demo? Thanks

**Comment by necmi** [comment]
+1

**Comment by F9Uf** [comment]
@chovy when i edit code follow you 

`const code = `process.chdir("${process.cwd().replace(/\\/g, "\\\\")}");``

There are some problems again. That is ...

> fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

**Comment by ThoughtZer** [comment]
@neeraj-singh47 It doesn't seem to have worked.

**Comment by neeraj-singh47** [comment]
@ThoughtZer What's the error? Can you specify the react-native-cli version using the command `react-native -v`?

**Comment by ThoughtZer** [comment]
@neeraj-singh47 Like this .... 
My net speed is too slow
![image](https://user-images.githubusercontent.com/23690568/41347392-16fae69a-6f3c-11e8-92c2-cf1295d7543e.png)

**Comment by tweetoxygen** [comment]
I also have the same error and I am currently running the latest version of React Native.

**Comment by neeraj-singh47** [comment]
It was an issue related to spawnSync where shell had to be specified for windows.

**Comment by tweetoxygen** [comment]
@neeraj-singh47 are you saying we can run it again now or?

**Comment by tweetoxygen** [comment]
@cfjedimaster when you say install again, are you referring to installing the vue-native-cli?

**Comment by tweetoxygen** [comment]
cfjedimaster thanks... After installing, tried to run npm start but I get an error saying missing script start. Tried with npm run but that also didnt seem to work.

**Comment by ThoughtZer** [comment]
@gauravprwl14 Thank you for fixing this problem.
@tweetoxygen maybe you should install again the vue-native-cli

**Comment by tweetoxygen** [comment]
@ThoughtZer I have done the installation all over again. The installation was successful. However, I am still having the issue with npm start. I keep getting missing script with that. For npm run, no error but nothing seems to be working. Is there something I need to do aside all the basic installations?
