### ISSUE TITLE
textinput can not input chinese character in real phone

### ISSUE THREAD

**Issue by lenvonsam** [GeekyAnts/vue-native-core#80]

**Comment by neeraj-singh47** [comment]
@lenvonsam Seems like issue is related to React Native 0.55. A quick fix would be 
```
<text-input
 :value="text"
  :on-change-text="text => text2=text"
 :on-blur="e => text = text2"
/>
```

**Comment by lenvonsam** [comment]
I have packaged TextInput with react component to make <text-input v-model="name"/> input chinese charaters come true by myself.
Anyway, thx
@neeraj-singh47
