### ISSUE TITLE
`class` with `render-prop-fn` is not working

### ISSUE THREAD

**Issue by woxtu** [GeekyAnts/vue-native-core#82]
Hi,

I tried to use `class` with `render-prop-fn`, and I got the following error. Is this correct behavior?

```vue
<template>
  <flat-list :data="[{key: 'a'}, {key: 'b'}]">
    <view render-prop-fn="renderItem" class="awesome-style">
      <text>{{args.item.key}}</text>
    </view>
  </flat-list>
</template>

<style>
.awesome-style {
}
</style>
```

```
TypeError: Cannot read property 'awesome-style' of undefined
```

vue-native-core@0.0.8, vue-native-helper@0.0.9, vue-native-scripts@0.0.14

**Comment by neeraj-singh47** [comment]
@woxtu Currently only inline styles are supported within render-prop-fn and render-prop.
