### ISSUE TITLE
render-prop with TabNavigator

### ISSUE THREAD

**Issue by LiveDuo** [GeekyAnts/vue-native-core#86]
I'm trying to implement a tab navigation icon that have a notification counter. 

![tdwym](https://user-images.githubusercontent.com/370612/45612161-d35a2480-ba6a-11e8-9805-bea69271e5bc.jpg)

Using a vue component instead would simplify the process. Can the new attributeds ie. render-prop and render-prop-fn help?

```
const TabNav = TabNavigator(
	{
		ProfileScreen: {
			screen: ProfileScreen,
			navigationOptions: ({ navigation }) => ({
				title: 'Profile',
				tabBarIcon: ({ focused, tintColor }) => { 
					return <MaterialCommunityIcons name="face=profile" size={32} color="#3B5998" />
				}
			})
		},
	},
    {
		tabBarOptions: {
			showIcon: true,
			showLabel: false,
		}
    }
 );
```

**Comment by neeraj-singh47** [comment]
@LiveDuo Sadly no. This is not possible since TabNavigator is a functional component and within definition we have to specify the icon. The render-prop and render-prop-fn would've helped if we could define routes within template

**Comment by LiveDuo** [comment]
Any workaround for this? Maybe a helper function that converts a Vue component to a React Native one.

**Comment by neeraj-singh47** [comment]
@LiveDuo We are actually converting a Vue Component to React Native but this is one specific use case where TabNavigation is a functional component and expects a React component to be returned. We'll have to wrap the TabNavigation so that it accepts a Vue Component

**Comment by LiveDuo** [comment]
Sure. I ended up writing React Native code. Looking forward for the wrapping!
