### ISSUE TITLE
React Native ref vs Vue Native ref

### ISSUE THREAD

**Issue by LiveDuo** [GeekyAnts/vue-native-core#89]
I'm trying to use navigation in the App.vue component to redirect push notification clicks to the appropriate screens. Reading through I found out that there seems to be a definitive way to achieve this as seen in the following examples.

> https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html
> https://github.com/react-navigation/react-navigation/issues/1439#issuecomment-303661539
> https://github.com/react-navigation/react-navigation/issues/1439#issuecomment-340293063

That is to use in one way or another the ref attribute on the main navigator component and the call this.navigator.dispatch to navigate to a different activity. Example follows.

```
<template>
  <View style="flex: 1;">
    <default-navigator :ref="nav => navigator = nav" />
  </View>
</template>

<script>
import DefaultNavigator from './router/StackNavigation'
export default {
  components: {
    DefaultNavigator
  },
  data () {
    return {
      navigator: undefined
    }
  },
  created() {
    this.navigator && this.navigator.dispatch({ type: 'Navigate', routeName: 'LoginScreen' });
  }
}
</script>
```

My problem seems to be that nor :ref="nav => navigator = nav" neither ref={nav => { this.navigator = nav; }} work and this.navigator return undefined.

Sorry about the long post.

**Comment by neeraj-singh47** [comment]
@LiveDuo For refs use this format while declaring `ref="nav"` and access them using this.$refs.nav. Although it'll be undefined within created method since the refs are not ready at the time of creation.

**Comment by brnmonteiro** [comment]
Hi!
I'm trying to use the [react-native-lottie](https://github.com/react-native-community/lottie-react-native)

The basic use in react is:

```javascript
import React from 'react';
import LottieView from 'lottie-react-native';

export default class BasicExample extends React.Component {
  render() {
    return <LottieView source={require('./animation.json')} loop="{false}" />;
  }
}
```

No problem. In Vue Native:

```javascript
<template>
  <view class="container">
    <lottie-view :source="require('./animation.json')" :loop="false" :onAnimationFinish="function() { console.log('finish') }" ref="animation" />  
  </view>
</template>
 
<script>
import LottieView from 'lottie-react-native';

export default {
  data: {
    animation:null,
  },
  mounted: function() {
    this.animation = this.$refs.animation;
    this.animation.play();
  },
  components: {
    LottieView
  }
}
</script>
<style>
.container {
  background-color: white;
  align-items: center;
  justify-content: center;
  flex: 1;
}
</style>
```
I can use and access the API using `"ref"` attr, but I can't make it work the `onAnimationFinish`. 

Any suggestion?
