### ISSUE TITLE
Please update library to work with React-Native 57+

### ISSUE THREAD

**Issue by fogil** [GeekyAnts/vue-native-core#91]
The current library supports up to and including RN 55, however this version of react-native has a show-stopping bug:  Hot-Reloading stops working after refreshing the app. (ref: https://github.com/facebook/react-native/issues/18899)  This bug is present on RN 51, 52, 53, 54, 55, 56, and is only fixed in the latest RN57.

**Comment by fogil** [comment]
I *believe* all that's needed is to update the rn-cli.config.js to this:
```
const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve("./vueTransformerPlugin.js")
    },
    resolver: {
      sourceExts: [...sourceExts, "vue"]
    }
  };
})();
```

**Comment by kida7** [comment]
> vueTransformerPlugin.js

hi bro, where is this file?

**Comment by fogil** [comment]
It's at https://vue-native.io/docs/installation.html  under the Setup with React Native section, Step 3

**Comment by jgiovanni** [comment]
Vue Native works with this configuration:
`react-native@0.57.4` + `react@16.5.1` + `react-test-renderer@16.6.0-alpha.8af6728`

```js
// vueTransformerPlugin.js
var semver = require('semver');
var vueNaiveScripts = require("vue-native-scripts");
var reactNativeVersionString = require("react-native/package.json").version;
var reactNativeMinorVersion = semver(reactNativeVersionString).minor;

if (reactNativeMinorVersion >= 56) {
  upstreamTransformer = require("metro/src/reactNativeTransformer");
} else if (reactNativeMinorVersion >= 52) {
  upstreamTransformer = require("metro/src/transformer");
} else if (reactNativeMinorVersion >= 47) {
  upstreamTransformer = require("metro-bundler/src/transformer");
} else if (reactNativeMinorVersion === 46) {
  upstreamTransformer = require("metro-bundler/build/transformer");
} else {
// handle RN <= 0.45
  var oldUpstreamTransformer = require("react-native/packager/transformer");
  upstreamTransformer = {
    transform({ src, filename, options }) {
      return oldUpstreamTransformer.transform(src, filename, options);
    }
  };
}
var vueExtensions = ["vue"]; // <-- Add other extensions if needed.

module.exports.transform = function({ src, filename, options }) {
  if (vueExtensions.some(ext => filename.endsWith("." + ext))) {
    return vueNaiveScripts.transform({ src, filename, options });
  }
  return upstreamTransformer.transform({ src, filename, options });
};
```

```js
// .babelrc
{
  "presets": [
    "module:metro-react-native-babel-preset"
  ]
}
```

**Comment by donvie** [comment]
@jgiovanni  I dont have .babelrc where can i find that what i have is babel.conifg.js

**Comment by donvie** [comment]
@jgiovanni Im using expo

**Comment by donvie** [comment]
![image](https://user-images.githubusercontent.com/6716238/48333202-75744280-e691-11e8-9dd0-cc179ae35f1f.png)

**Comment by donvie** [comment]
the my vue native app is on the header

**Comment by divrse** [comment]
> the my vue native app is on the header

@donvie have you found a fix for this?  my app is also appearing on the top of the screen after I changed the rn-cli file.

**Comment by nucreativa** [comment]
same here, please share your fix for this issue (appearing on the top and css not working)

**Comment by divrse** [comment]
@nucreativa I gave up on using the latest version of react native and followed the instructions here https://github.com/GeekyAnts/vue-native-core/issues/101#issuecomment-437606353 to downgrade
and got it working

**Comment by xcxooxl** [comment]
I also got it "working" with the latest react-native,

create a file in your main project directory

metro.config.js : 
```
module.exports = {
    transformer: {
        babelTransformerPath: '../../../../vueTransformerPlugin.js'
    },
    resolver: {
        sourceExts: ['vue','js', 'json', 'ts', 'tsx', 'jsx']
    }
};

```

.babelrc: 
```
{
  "presets": ["module:metro-react-native-babel-preset"]
}
```

package.json: 

```
  "dependencies": {
    "react": "16.7.0",
    "react-native": "0.57.8",
    "vue-native-core": "0.0.8",
    "vue-native-helper": "0.0.9",
    "vue-native-router": "0.0.1-alpha.3",
    "vuex": "^3.0.1"
  },

```

**Comment by lucasromanojf** [comment]
Expo is now on 32.0.0 and supporting RN 0.57. Would be good if Vue Native could follow.

**Comment by neeraj-singh47** [comment]
Thank you @fogil. @lucasromanojf  Support for RN > 0.55 has been added. Please update vue-native-cli to create  a new app with RN version > 0.55. [ Latest Release](https://github.com/GeekyAnts/vue-native-cli/releases/tag/0.0.6)
