### ISSUE TITLE
How to set up a code editor for comfortable development with vue-native?

### ISSUE THREAD

**Issue by RomanMarkelov** [GeekyAnts/vue-native-core#93]
How to set up code editors like ( [vscode](https://github.com/Microsoft/vscode), [webstorm](https://www.jetbrains.com/webstorm/) ) for comfortable development with vue-native?

Share please yours settings, plugins, etc which you use 🙂

**Comment by neeraj-singh47** [comment]
@RomanMarkelov You can make use of `vue` plugin in vscode for syntax highlights

**Comment by RomanMarkelov** [comment]
@neeraj-singh47  I thought I'd find out something new.

That's what's missing:

- [ ] Autocomplete

![screenshot 2018-10-22 08 13 12](https://user-images.githubusercontent.com/12942199/47278522-650d0280-d5d2-11e8-8414-071df7415b9d.png)

This also applies to components.
