### ISSUE TITLE
Vue Native init breaks due to 'react-native-scripts'

### ISSUE THREAD

**Issue by javico2609** [GeekyAnts/vue-native-core#98]
UnhandledPromiseRejectionWarning: Error: Cannot find module '\demos\vueNative\node_modules\react-native-scripts\build\scripts\init.js'

**Comment by neeraj-singh47** [comment]
@javico2609 You might have to update the vue-native cli and install expo cli as well? Which version of vue-native-cli are you using?

**Comment by neeraj-singh47** [comment]
@javico2609 Can you try npm install -g create-react-native-app and try again

**Comment by javico2609** [comment]
@neeraj-singh47 tnx that fix the issue
