### ISSUE TITLE
Can't pass arguments to button :on-press function

### ISSUE THREAD

**Issue by mgween** [GeekyAnts/vue-native-core#99]
Making the following modification to the example for the Button component causes the function to be run immediately and gives the error: `Warning: Failed prop type: The prop 'onPress' is marked as required in 'Button', but its value is 'undefined'.` The button will then not work any further.

`<button
    :on-press="onPressLearnMore('Hello')"
     title="Learn More"
 />`
`onPressLearnMore: function(arg) {
    alert(arg)
}`

I want to use the button in a list generated with `v-for`. So I need to be able to pass an argument of the list item that the button was pressed for. How can I accomplish this?

**Comment by neeraj-singh47** [comment]
@mgween If you want to pass argument. The format should be `:on-press="() => OnPressLearnMore('hello')".
